import { test, expect } from '@playwright/test'
import { generateRoomSecret } from '../src/room.js'
import { encodeRoomLink } from '../src/link.js'
import { RoomAgent } from '../src/agent.js'
import { generateSecretKey, finalizeEvent } from 'nostr-tools/pure'
import { localIdentity } from '../src/identity.js'
import { NostrRelayPool } from '../src/relay-pool.js'
import { reactionText, toggleReaction } from '../src/reactions.js'
import { openRoomDetails } from './browser.js'

test('timestamps, avatars, direct search, emoji insertion and encrypted reaction toggles work together', async ({ browser, baseURL }) => {
  const relay = new URL('/__test-relay', baseURL); relay.protocol = 'wss:'
  const context = await browser.newContext({ ignoreHTTPSErrors: true, serviceWorkers: 'block', viewport: { width: 390, height: 844 } })
  await context.routeWebSocket(url => url.href !== relay.href, ws => ws.close())
  await context.route('**/turn', route => route.fulfill({ status: 503, body: '' }))
  const link = encodeRoomLink(baseURL!, { secret: generateRoomSecret(), name: 'Workshop', relays: [relay.href], iceUrls: [] })
  const profileKey = generateSecretKey()
  const identity = localIdentity(profileKey)
  const publisher = new NostrRelayPool(['ws://127.0.0.1:7777'])
  const pictureURL = 'https://profiles.example/rowan.svg'
  let pictureRequests = 0
  await context.route(pictureURL, route => { pictureRequests++; return route.fulfill({ contentType: 'image/svg+xml', body: '<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32"><rect width="32" height="32" fill="teal"/></svg>' }) })
  await publisher.publish(finalizeEvent({ kind: 0, created_at: Math.floor(Date.now() / 1000), tags: [], content: JSON.stringify({ name: 'Rowan', picture: pictureURL }) }, profileKey))
  const writer = await RoomAgent.join({ link, identity, relays: ['ws://127.0.0.1:7777'], name: 'Rowan' })
  try {
    const page = await context.newPage(); await page.goto(link)
    await page.locator('#displayName').fill('Ada'); await page.locator('#join').click()
    await writer.chat.send('Where is the toolbox?')
    const row = page.locator('#chatLog .msg').filter({ hasText: 'Where is the toolbox?' })
    await expect(row.locator('.messageHeader time')).toHaveAttribute('datetime', /T/)
    await expect(row.locator('.messageHeader time')).toContainText(/\d{1,2}:\d{2}/)
    await expect(row.locator('img.avatar')).toHaveAttribute('src', pictureURL)
    // WebKit reports an SVG's rendered intrinsic size here. Verify decoding
    // independently of that engine-specific size; the source is checked above.
    await expect.poll(() => row.locator('img.avatar').evaluate((img: HTMLImageElement) => img.complete && img.naturalWidth > 0 && img.naturalHeight > 0)).toBe(true)
    expect(pictureRequests).toBeGreaterThan(0)
    await openRoomDetails(page); await page.locator('#roomProfileSettings').click(); await page.locator('#lookupProfiles').uncheck(); await page.locator('#profileSettingsClose').click()
    await expect(row.locator('.avatar.initials')).toBeVisible()
    await expect(row.locator('img.avatar')).toHaveCount(0)
    await page.locator('#chatInput').fill('before after')
    await page.locator('#chatInput').evaluate((el: HTMLTextAreaElement) => el.setSelectionRange(7, 7))
    await page.locator('#emojiToggle').click(); await page.getByRole('searchbox', { name: 'Search emoji' }).fill('head against wall')
    await page.getByRole('button', { name: /🤦 facepalm/ }).click()
    await expect(page.locator('#chatInput')).toHaveValue('before 🤦after')
    await expect(page.locator('#chatInput')).toBeFocused()
    await page.locator('#chatSearch').click(); await page.locator('#messageSearchQuery').fill('toolbox')
    await expect(page.locator('#messageSearchResults li')).toHaveCount(1)
    await page.locator('#messageSearchClose').click(); await expect(page.locator('#chatSearch')).toBeFocused()
    await expect(page.locator('#chatInput')).toHaveValue('before 🤦after')
    await row.getByRole('button', { name: /^React to message from Rowan/ }).click()
    await page.locator('#messageActionPanel').getByRole('button', { name: 'Add ❤️ reaction', exact: true }).click()
    await expect(row.getByRole('button', { name: 'Remove ❤️ reaction, 1', exact: true })).toHaveAttribute('aria-pressed', 'true')
    const target = writer.chat.messages().find(m => m.text === 'Where is the toolbox?')!
    const reaction = toggleReaction(writer.chat.messages(), target, target.participant, '❤️')
    await writer.chat.send(reactionText(reaction), { reaction })
    const hearts = row.getByRole('button', { name: 'Remove ❤️ reaction, 2', exact: true })
    await expect(hearts).toBeVisible()
    await hearts.hover()
    await expect(row.getByRole('tooltip')).toBeVisible()
    await expect(row.getByRole('tooltip')).toContainText('Rowan')
    await expect(row.getByRole('tooltip')).toContainText('Ada')
    await row.getByRole('button', { name: /^React to message from Rowan/ }).click()
    await page.locator('#messageActionPanel').getByRole('button', { name: 'Add 😂 reaction', exact: true }).click()
    const laugh = row.getByRole('button', { name: 'Remove 😂 reaction, 1', exact: true })
    await expect(laugh).toHaveAttribute('aria-pressed', 'true')
    await expect(hearts).toHaveAttribute('aria-pressed', 'true')
    await laugh.focus()
    await expect(row.getByRole('tooltip').filter({ hasText: '😂' })).toContainText('Ada')
    await laugh.click()
    await row.getByRole('button', { name: 'Remove ❤️ reaction, 2', exact: true }).click()
    await expect(row.getByRole('button', { name: 'Add ❤️ reaction, 1', exact: true })).toHaveAttribute('aria-pressed', 'false')
    await expect(page.locator('#chatLog .msg')).toHaveCount(1)
    await page.locator('#chatForm button[type=submit]').click()
    await expect(page.locator('#chatLog .mine .text')).toHaveText('before 🤦after')
    await page.setViewportSize({ width: 320, height: 700 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.screenshot({ path: `/tmp/kithmoot-chat-320-${test.info().project.name}.png` })
  } finally { await writer.leave(); publisher.close(); await context.close() }
})

test('busy conversations group senders and keep a stable, keyboard-accessible action panel through incoming edits', async ({ browser, baseURL }, testInfo) => {
  const relay = new URL('/__test-relay', baseURL); relay.protocol = 'wss:'
  const context = await browser.newContext({ ignoreHTTPSErrors: true, serviceWorkers: 'block', viewport: { width: 390, height: 844 } })
  await context.routeWebSocket(url => url.href !== relay.href, ws => ws.close())
  await context.route('**/turn', route => route.fulfill({ status: 503, body: '' }))
  const link = encodeRoomLink(baseURL!, { secret: generateRoomSecret(), name: 'Workshop', relays: [relay.href], iceUrls: [] })
  let sentAt = Math.floor(Date.now() / 1000) - 700
  const writer = await RoomAgent.join({ link, relays: ['ws://127.0.0.1:7777'], name: 'Rowan', agent: false, now: () => sentAt })
  const other = await RoomAgent.join({ link, relays: ['ws://127.0.0.1:7777'], name: 'Rowan', agent: false, now: () => sentAt })
  try {
    const page = await context.newPage(); await page.goto(link)
    await page.locator('#displayName').fill('Ada'); await page.locator('#join').click()
    for (const text of ['The workshop is booked.', 'We have the room until five.', 'Bring the projector.', 'Tea and coffee are sorted.', 'The draft is ready.', 'Please review the agenda.']) { sentAt++; await writer.chat.send(text) }
    const rows = page.locator('#chatLog .msg')
    await expect(rows).toHaveCount(6)
    await expect(page.locator('#chatLog .msg.continuation')).toHaveCount(5)
    await expect(rows.locator('time')).toHaveCount(6)
    await expect(rows.locator('.messageReactions')).toHaveCount(0)
    await expect(rows.getByRole('button')).toHaveCount(12)
    // The same displayed name is not evidence that two senders are one person.
    sentAt++; await other.chat.send('Another Rowan, with a different key.')
    const namesake = rows.filter({ hasText: 'Another Rowan' })
    await expect(namesake).not.toHaveClass(/continuation/)
    sentAt++; await writer.chat.send('I will bring the handouts.')
    sentAt += 301; await writer.chat.send('An update after the break.')
    await expect(rows.filter({ hasText: 'An update after the break.' })).not.toHaveClass(/continuation/)
    await page.locator('#chatInput').fill('Keep my unfinished reply')
    const original = writer.chat.messages().find(message => message.text === 'Please review the agenda.')!
    const more = page.locator(`#chatLog [data-message-id="${original.id}"] .messageMore`)
    await more.focus(); await more.press('Enter')
    const panel = page.getByRole('dialog', { name: 'Message actions', exact: true })
    await expect(panel).toBeVisible()
    const reply = panel.getByRole('button', { name: /^Reply to Rowan/ })
    await expect(reply).toBeFocused()
    await page.keyboard.press('Tab')
    await expect(panel.getByRole('button', { name: 'Add 👍 reaction', exact: true })).toBeFocused()
    await page.keyboard.press('Shift+Tab')
    await expect(reply).toBeFocused()
    await expect(panel.getByRole('button', { name: 'Edit this message', exact: true })).toHaveCount(0)
    await expect(panel.getByRole('group', { name: 'React to this message' }).getByRole('button')).toHaveCount(8)
    sentAt++; await writer.chat.send('The conversation continues while actions are open.')
    await expect(rows).toHaveCount(10)
    await expect(reply).toBeFocused()
    sentAt++; await writer.chat.send('Please review the revised agenda.', { replaces: original.id })
    await expect(panel.locator('.messageActionPreview')).toHaveText('Please review the revised agenda.')
    await expect(reply).toBeFocused()
    await page.keyboard.press('Escape')
    await expect(panel).not.toBeVisible()
    await expect(more).toBeFocused()
    await expect(page.locator('#chatInput')).toHaveValue('Keep my unfinished reply')
    await more.click()
    await page.locator('#chatInput').click()
    await expect(panel).not.toBeVisible()
    await expect(page.locator('#chatInput')).toBeFocused()
    await more.click()
    await panel.getByRole('button', { name: 'Add 🎉 reaction', exact: true }).click()
    const updated = page.locator(`#chatLog [data-message-id="${original.id}"]`)
    await expect(updated.getByRole('button', { name: 'Remove 🎉 reaction, 1', exact: true })).toBeVisible()
    await updated.getByRole('button', { name: 'Remove 🎉 reaction, 1', exact: true }).click()
    await expect(updated.locator('.messageReactions')).toHaveCount(0)
    // The panel fits both edges of the phone, both themes and enlarged text.
    for (const colorScheme of ['light', 'dark'] as const) {
      await page.emulateMedia({ colorScheme })
      for (const width of [320, 390, 1440]) {
        await page.setViewportSize({ width, height: 740 })
        await more.scrollIntoViewIfNeeded()
        await page.screenshot({ path: testInfo.outputPath(`conversation-${colorScheme}-${width}.png`) })
        await more.click()
        await expect(panel).toBeInViewport()
        const bounds = await panel.boundingBox()
        expect(bounds!.x).toBeGreaterThanOrEqual(0)
        expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(width)
        expect(await panel.evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true)
        await page.screenshot({ path: testInfo.outputPath(`message-actions-${colorScheme}-${width}.png`) })
        await page.keyboard.press('Escape')
      }
    }
    // Arrivals covered by an action panel stay unread until it closes.
    await page.locator('#chatLog').evaluate(el => { el.scrollTop = el.scrollHeight })
    const unread = page.locator('#conversationNav button[data-channel=""] .conversationUnread')
    await expect(unread).toHaveCount(0)
    await rows.last().locator('.messageMore').click()
    sentAt++; await writer.chat.send('An arrival behind the actions.')
    await expect(unread).toHaveText('1')
    await page.keyboard.press('Escape')
    await expect(unread).toHaveCount(0)
    await page.setViewportSize({ width: 320, height: 540 })
    await page.evaluate(() => { document.documentElement.style.fontSize = '200%' })
    await more.click()
    expect(await panel.evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true)
    await panel.getByRole('button', { name: /^Reply to Rowan/ }).click()
    await expect(page.locator('#composerContext')).toContainText('Replying to Rowan')
    await expect(page.locator('#composerContext .contextExcerpt')).toHaveText('Please review the revised agenda.')
    await expect(page.locator('#chatInput')).toHaveValue('Keep my unfinished reply')
    await expect(page.locator('#chatInput')).toBeFocused()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.screenshot({ path: testInfo.outputPath('conversation-large-text.png') })
    await more.click()
    sentAt++; await writer.chat.send('Retracted the agenda request', { retracts: original.id })
    await expect(panel).not.toBeVisible()
    await expect(updated.locator('.messageMore')).toHaveCount(0)
    await expect(page.locator('#chatInput')).toHaveValue('Keep my unfinished reply')
  } finally { writer.leave(); other.leave(); await context.close() }
})
