import { test, expect, type BrowserContext, type Page } from '@playwright/test'
import { build } from 'esbuild'
import { readFileSync } from 'node:fs'
import { ed25519 } from '@noble/curves/ed25519.js'
import { sha256 } from '@noble/hashes/sha2.js'
import { bytesToHex, hexToBytes, concatBytes } from '@noble/hashes/utils.js'
import { pairingFixture } from './mls-pairing-fixture.js'
const origin = 'https://browser-mls-rooms.kithmoot.test'
let bundle: string
test.beforeAll(async () => { bundle = (await build({ entryPoints: ['test/mls-room-operations.browser-entry.ts'], bundle: true, write: false, format: 'iife', globalName: 'M', define: { 'import.meta.env.BASE_URL': '"/"' } })).outputFiles[0].text })
async function fixture(context: BrowserContext) {
  const key = new Uint8Array(32).fill(91)
  const witness = { seq: 0n, digest: new Uint8Array(32), offline: false, refused: false, loseAdvance: false, wrongKey: false, replay: false, retired: false, advances: 0, reads: 0, last: undefined as number[] | undefined, advancePause: undefined as Promise<void> | undefined }
  await context.exposeBinding('loseNextWitnessAdvance', () => { witness.loseAdvance = true })
  await context.exposeBinding('witnessExchange', async (_, method: string, input: number[]) => {
    if (witness.offline) return { type: 'unavailable' }
    if (witness.refused) return { type: 'refused' }
    const request = new Uint8Array(input)
    expect(request.length).toBe(method === 'read' ? 73 : 145)
    let status = witness.retired ? 2 : 0
    if (method === 'advance') {
      witness.advances++
      await witness.advancePause
      // These bounded fixtures stay below the one-byte CBOR integer boundary.
      const expected = BigInt(request[39])
      if (!witness.retired && witness.seq === expected && bytesToHex(witness.digest) === bytesToHex(request.subarray(43, 75))) { witness.seq++; witness.digest = request.slice(78, 110) }
      else if (!witness.retired && witness.seq < expected) { witness.retired = true; status = 2 }
      else if (!witness.retired) status = 1
      if (witness.loseAdvance) { witness.loseAdvance = false; return { type: 'unavailable' } }
    } else {
      witness.reads++
      if (witness.replay && witness.last) return { type: 'receipt', bytes: witness.last }
    }
    const signed = new Uint8Array(106)
    signed[0] = 1; signed[1] = status; signed.set(request.subarray(6, 38), 2)
    new DataView(signed.buffer).setBigUint64(34, witness.seq)
    signed.set(witness.digest, 42); signed.set(request.subarray(request.length - 32), 74)
    const digest = sha256(concatBytes(new TextEncoder().encode('VMLS/1 witness receipt'), signed))
    const bytes = Array.from(concatBytes(signed, ed25519.sign(digest, witness.wrongKey ? new Uint8Array(32).fill(92) : key)))
    if (method === 'read') witness.last = bytes
    return { type: 'receipt', bytes }
  })
  await context.route(origin + '/**', route => {
    const path = new URL(route.request().url()).pathname
    if (path === '/') return route.fulfill({ contentType: 'text/html', headers: { 'Content-Security-Policy': "default-src 'self'; script-src 'self' 'wasm-unsafe-eval'" }, body: '<script src="/fixture.js"></script>' })
    if (path === '/fixture.js') return route.fulfill({ contentType: 'text/javascript', body: bundle })
    if (path === '/vmls-wasm/vmls_wasm.js' || path === '/vmls-wasm/vmls_wasm_bg.wasm') return route.fulfill({ contentType: path.endsWith('.wasm') ? 'application/wasm' : 'text/javascript', body: readFileSync('app/public' + path) })
    return route.abort()
  })
  const page = await context.newPage()
  await page.goto(origin)
  const ids = await page.evaluate(route => (window as any).M.prepare(route), pairingFixture(key).route)
  witness.digest = new Uint8Array(hexToBytes(ids.digest))
  return { page, witness, ids }
}
const run = (page: Page, code: string): Promise<any> => page.evaluate(code)
async function enrolled(context: BrowserContext, room = true) {
  const f = await fixture(context)
  expect(await run(f.page, 'M.enrol()')).toMatchObject({ ok: true })
  if (room) { const created = await run(f.page, 'M.create()'); expect(created).toMatchObject({ state: 'active' }) }
  return f
}
async function joinedWithMemberDevice(page: Page) {
  await run(page, 'M.provisionJoin()')
  expect(await run(page, 'M.typedJoin()')).toMatchObject({ state: 'active' })
  expect(await run(page, 'M.makeJoinWelcome()')).toBe(true)
  expect(await run(page, 'M.acceptJoinWelcome()')).toMatchObject({ state: 'active', value: { outcome: { type: 'Accepted' } } })
  expect(await run(page, 'M.firstJoinUpdate()')).toMatchObject({ state: 'active' })
  expect(await run(page, 'M.addJoinedMemberDevice()')).toBe('active')
}
test('device install hold blocks existing and new nodes across tabs while another device remains independent', async ({ context }) => {
  const { page } = await enrolled(context, false)
  const existing = await run(page, 'M.startFenceInstall(77)')
  expect(await page.evaluate(key => (window as any).M.finishFenceInstall(key), existing)).toMatchObject({ state: 'installed' })
  const other = await context.newPage(); await other.goto(origin)
  await run(page, 'M.startFenceHold()')
  const first = await run(other, 'M.startFenceInstall(77)'), second = await run(other, 'M.startFenceInstall(78)')
  await expect.poll(async () => (await run(other, 'M.fenceSnapshot()')).pending.filter((lock: any) => lock.name.startsWith('kithmoot.vmls-grant-install.')).length).toBe(2)
  expect((await run(other, 'M.fenceSnapshot()')).publications).toEqual([])
  const unrelated = await run(other, `M.startFenceInstall(77, '${'65'.repeat(32)}')`)
  expect(await other.evaluate(key => (window as any).M.finishFenceInstall(key), unrelated)).toMatchObject({ state: 'installed' })
  expect(await run(page, 'M.finishFenceHold()')).toEqual({ value: 'settled' })
  for (const key of [first, second]) expect(await other.evaluate(key => (window as any).M.finishFenceInstall(key), key)).toMatchObject({ state: 'installed' })
  expect((await run(other, 'M.fenceSnapshot()')).records).toHaveLength(3)
})
test('shared installations at distinct nodes stay concurrent and an exclusive hold waits for actual publication settlement', async ({ context }) => {
  const { page } = await enrolled(context, false)
  await run(page, 'M.pauseFencePublications()')
  const first = await run(page, 'M.startFenceInstall(77)'), second = await run(page, 'M.startFenceInstall(78)')
  await expect.poll(async () => (await run(page, 'M.fenceSnapshot()')).publications.length).toBe(2)
  await run(page, 'M.startFenceHold(false)')
  await expect.poll(async () => (await run(page, 'M.fenceSnapshot()')).pending.some((lock: any) => lock.name.startsWith('kithmoot.vmls-grant-install.') && lock.mode === 'exclusive')).toBe(true)
  expect((await run(page, 'M.fenceSnapshot()')).work).toBe(0)
  await run(page, 'M.resumeFencePublications()')
  for (const key of [first, second]) expect(await page.evaluate(key => (window as any).M.finishFenceInstall(key), key)).toMatchObject({ state: 'installed' })
  await expect.poll(async () => (await run(page, 'M.fenceSnapshot()')).work).toBe(1)
  expect(await run(page, 'M.finishFenceHold()')).toEqual({ value: 'settled' })
})
for (const mode of ['reject', 'account', 'foreground'] as const) test(`device install hold remains held until a ${mode} callback actually settles`, async ({ context }) => {
  const { page } = await enrolled(context, false)
  const other = await context.newPage(); await other.goto(origin)
  await page.evaluate(reject => (window as any).M.startFenceHold(true, reject), mode === 'reject')
  const key = await run(other, 'M.startFenceInstall(78)')
  await expect.poll(async () => (await run(other, 'M.fenceSnapshot()')).pending.some((lock: any) => lock.name.startsWith('kithmoot.vmls-grant-install.'))).toBe(true)
  if (mode !== 'reject') await run(page, mode === 'account' ? 'M.changeFenceAccount()' : 'M.hideFenceForeground()')
  expect((await run(other, 'M.fenceSnapshot()')).publications).toEqual([])
  expect(await run(page, 'M.finishFenceHold()')).toMatchObject({ error: mode === 'reject' ? 'fixture witness rejected' : 'fixture callback stale' })
  expect(await other.evaluate(key => (window as any).M.finishFenceInstall(key), key)).toMatchObject({ state: 'installed' })
})
test('an account change while an install hold is queued never enters its completion callback', async ({ context }) => {
  const { page } = await enrolled(context, false)
  await run(page, 'M.pauseFencePublications()')
  const key = await run(page, 'M.startFenceInstall(77)')
  await expect.poll(async () => (await run(page, 'M.fenceSnapshot()')).publications.length).toBe(1)
  await run(page, 'M.startFenceHold(false)')
  await expect.poll(async () => (await run(page, 'M.fenceSnapshot()')).pending.some((lock: any) => lock.mode === 'exclusive' && lock.name.startsWith('kithmoot.vmls-grant-install.'))).toBe(true)
  await run(page, 'M.changeFenceAccount(); M.resumeFencePublications()')
  expect(await page.evaluate(key => (window as any).M.finishFenceInstall(key), key)).toMatchObject({ error: 'Sign in as this grant’s keeper before changing VMLS access.' })
  expect(await run(page, 'M.finishFenceHold()')).toMatchObject({ error: 'The keeper account or foreground session changed.' })
  expect((await run(page, 'M.fenceSnapshot()')).work).toBe(0)
})
test('queued installations recheck the captured keeper before signing or mutating the ledger', async ({ context }) => {
  const { page } = await enrolled(context, false)
  await run(page, 'M.startFenceHold()')
  const key = await run(page, 'M.startFenceInstall(77)')
  await expect.poll(async () => (await run(page, 'M.fenceSnapshot()')).pending.some((lock: any) => lock.mode === 'shared' && lock.name.startsWith('kithmoot.vmls-grant-install.'))).toBe(true)
  await run(page, 'M.changeFenceAccount()')
  expect(await run(page, 'M.finishFenceHold()')).toMatchObject({ error: 'fixture callback stale' })
  expect(await page.evaluate(key => (window as any).M.finishFenceInstall(key), key)).toMatchObject({ error: 'Sign in as this grant’s keeper before changing VMLS access.' })
  const snapshot = await run(page, 'M.fenceSnapshot()')
  expect(snapshot.publications).toEqual([]); expect(snapshot.records).toEqual([])
})
test('same-node installs remain serial while another node can publish under the shared device gate', async ({ context }) => {
  const { page } = await enrolled(context, false)
  await run(page, 'M.pauseFencePublications()')
  const first = await run(page, 'M.startFenceInstall(77)'), repeated = await run(page, 'M.startFenceInstall(77)'), other = await run(page, 'M.startFenceInstall(78)')
  await expect.poll(async () => (await run(page, 'M.fenceSnapshot()')).publications.length).toBe(2)
  const snapshot = await run(page, 'M.fenceSnapshot()')
  expect(snapshot.pending.some((lock: any) => lock.name.startsWith('kithmoot.vmls-grant.') && !lock.name.startsWith('kithmoot.vmls-grant-install.'))).toBe(true)
  await run(page, 'M.resumeFencePublications()')
  for (const key of [first, repeated, other]) expect(await page.evaluate(key => (window as any).M.finishFenceInstall(key), key)).toMatchObject({ state: 'installed' })
  expect((await run(page, 'M.fenceSnapshot()')).publications).toHaveLength(2)
})
for (const stage of ['sign', 'installing', 'publish', 'active']) test(`keeper approval waits for ${stage} installation settlement and rejects the stale reviewed authority`, async ({ context }) => {
  const { page } = await enrolled(context)
  await run(page, 'M.addGuest(false, undefined, false, true)'); await run(page, 'M.receiveKeeperRequest()')
  const plan = await run(page, 'M.keeperDecisionPlan()')
  expect(plan.state).toBe('active')
  await page.evaluate(stage => (window as any).M.beginKeeperInstall(stage), stage)
  await page.evaluate(plan => (window as any).M.beginKeeperApproval(plan), plan.value)
  await expect.poll(() => page.evaluate(async () => (await navigator.locks.query()).pending?.some(lock => lock.name?.startsWith('kithmoot.vmls-grant-install.') && lock.mode === 'exclusive'))).toBe(true)
  expect(await run(page, 'M.keeperApprovals(true)')).toMatchObject({ value: [] })
  expect(await run(page, 'M.finishKeeperInstall()')).toEqual({ state: 'active' })
  expect(await run(page, 'M.finishKeeperApproval()')).toMatchObject({ error: expect.stringContaining('authority changed') })
  expect(await run(page, 'M.decideKeeperRequest()')).toMatchObject({ state: 'active', value: { state: 'approved' } })
  await run(page, 'M.forgetGuest()')
})
test('a queued install sees the durable hold only after keeper approval witness settlement', async ({ context }) => {
  const { page, witness } = await enrolled(context)
  await run(page, 'M.addGuest(false, undefined, false, true)'); await run(page, 'M.receiveKeeperRequest()')
  const plan = await run(page, 'M.keeperDecisionPlan()'), before = witness.advances
  let release!: () => void
  witness.advancePause = new Promise<void>(resolve => { release = resolve })
  await page.evaluate(plan => (window as any).M.beginKeeperApproval(plan), plan.value)
  await expect.poll(() => witness.advances).toBeGreaterThan(before)
  await run(page, "M.beginKeeperInstall('', false)")
  await expect.poll(() => page.evaluate(async () => (await navigator.locks.query()).pending?.some(lock => lock.name?.startsWith('kithmoot.vmls-grant-install.') && lock.mode === 'shared'))).toBe(true)
  release(); witness.advancePause = undefined
  expect(await run(page, 'M.finishKeeperApproval()')).toMatchObject({ result: { state: 'active', value: { state: 'approved' } } })
  expect(await run(page, 'M.finishKeeperInstall()')).toMatchObject({ error: expect.stringContaining('retained keeper revocation hold') })
  expect(await run(page, "M.keeperInstallAttempt('new')")).toMatchObject({ error: expect.stringContaining('retained keeper revocation hold'), signed: 0, writes: 0, published: 0 })
  await run(page, 'M.forgetGuest()')
})
for (const terminal of [false, true]) test(`keeper ${terminal ? 'done' : 'approved deferred'} device hold blocks existing and new nodes after restart and request expiry`, async ({ context }) => {
  const { page } = await enrolled(context)
  await run(page, 'M.addGuest(false, undefined, false, true)'); await run(page, 'M.receiveKeeperRequest(false, true, 60)')
  if (terminal) {
    await run(page, 'M.approveKeeperRequest()'); await run(page, 'M.applyKeeperRemoval()')
    expect(await run(page, 'M.continueKeeperRequest()')).toMatchObject({ state: 'done' })
  } else { await run(page, 'M.decideKeeperRequest()'); await run(page, 'M.deferKeeperRequest()') }
  await run(page, 'M.restart(); M.advance(61)')
  for (const node of ['current', 'new']) expect(await page.evaluate(node => (window as any).M.keeperInstallAttempt(node), node)).toMatchObject({ error: expect.stringContaining('retained keeper revocation hold'), signed: 0, writes: 0, published: 0 })
  await run(page, 'M.forgetGuest()')
})
test('keeper admission witness outage refuses an install before signing, writing or publishing', async ({ context }) => {
  const { page, witness } = await enrolled(context)
  await run(page, 'M.addGuest(false, undefined, false, true)'); await run(page, 'M.receiveKeeperRequest()')
  witness.offline = true
  expect(await run(page, "M.keeperInstallAttempt('new')")).toMatchObject({ error: expect.stringContaining('fresh witnessed keeper admission'), signed: 0, writes: 0, published: 0 })
  witness.offline = false
  await run(page, 'M.forgetGuest()')
})
for (const terminal of [false, true]) for (const conflict of [false, true]) test(`candidate Add refuses ${terminal ? 'done' : 'approved deferred'} ${conflict ? 'different-person' : 'same-person'} device after expiry and restart before package registration`, async ({ context }) => {
  const { page } = await enrolled(context)
  await run(page, `M.candidateKeeperHold('${terminal ? 'done' : 'approved'}')`)
  if (!terminal) await run(page, 'M.deferKeeperRequest()')
  await run(page, 'M.advance(61); M.restart()')
  const before = await run(page, 'M.read()'), retained = await run(page, 'M.keeperApprovals(true)')
  await run(page, `M.beginCandidateAdd(${conflict})`)
  expect(await run(page, 'M.finishCandidateAdd()')).toEqual({ state: 'refused', reason: conflict ? 'device-person-conflict' : 'compromised-device-admission' })
  expect(await run(page, 'M.candidateAddSnapshot()')).toMatchObject({ registrations: 0 })
  expect(await run(page, 'M.read()')).toEqual(before)
  expect(await run(page, 'M.keeperApprovals(true)')).toEqual(retained)
  await run(page, 'M.forgetGuest()')
})
for (const state of ['pending', 'dismissed']) test(`candidate Add admits an unheld device with a ${state} keeper prompt`, async ({ context }) => {
  const { page } = await enrolled(context)
  await run(page, `M.candidateKeeperHold('${state}'); M.beginCandidateAdd()`)
  expect(await run(page, 'M.finishCandidateAdd()')).toBe('active')
  expect(await run(page, 'M.candidateAddSnapshot()')).toMatchObject({ registrations: 1 })
  await run(page, 'M.forgetGuest()')
})
test('candidate Add keeps approval outside the device gate through actual package registration', async ({ context }) => {
  const { page } = await enrolled(context)
  await run(page, "M.candidateKeeperHold('pending')")
  const plan = await run(page, 'M.keeperDecisionPlan()')
  await run(page, 'M.pauseCandidatePackages(); M.beginCandidateAdd()')
  await expect.poll(async () => (await run(page, 'M.candidateAddSnapshot()')).registrations).toBe(1)
  await page.evaluate(plan => (window as any).M.beginKeeperApproval(plan), plan.value)
  await expect.poll(() => page.evaluate(async () => (await navigator.locks.query()).pending?.some(lock => lock.name?.startsWith('kithmoot.vmls-grant-install.') && lock.mode === 'exclusive'))).toBe(true)
  expect(await run(page, 'M.keeperApprovals(true)')).toMatchObject({ state: 'active', value: [] })
  await run(page, 'M.releaseCandidatePackages()')
  expect(await run(page, 'M.finishCandidateAdd()')).toBe('active')
  // The Add proposal precedes this approval. Its later box readback is a
  // separate pending-Add composition boundary, not covered by admission.
  expect(await run(page, 'M.finishKeeperApproval()')).toMatchObject({ result: { state: 'active', value: { state: 'approved' } } })
  await run(page, 'M.forgetGuest()')
})
test('candidate Add queued behind approval sees the witnessed device hold before package registration', async ({ context }) => {
  const { page, witness } = await enrolled(context)
  await run(page, "M.candidateKeeperHold('pending')")
  const plan = await run(page, 'M.keeperDecisionPlan()'), before = witness.advances
  await run(page, 'M.pauseCandidateStart(); M.beginCandidateAdd()')
  await expect.poll(async () => (await run(page, 'M.candidateAddSnapshot()')).prepared).toBe(true)
  let release!: () => void
  witness.advancePause = new Promise<void>(resolve => { release = resolve })
  await page.evaluate(plan => (window as any).M.beginKeeperApproval(plan), plan.value)
  await expect.poll(() => witness.advances).toBeGreaterThan(before)
  await run(page, 'M.releaseCandidateStartPause()')
  await expect.poll(() => page.evaluate(async () => (await navigator.locks.query()).pending?.some(lock => lock.name?.startsWith('kithmoot.vmls-grant-install.') && lock.mode === 'shared'))).toBe(true)
  expect(await run(page, 'M.candidateAddSnapshot()')).toMatchObject({ registrations: 0 })
  release(); witness.advancePause = undefined
  expect(await run(page, 'M.finishKeeperApproval()')).toMatchObject({ result: { state: 'active' } })
  expect(await run(page, 'M.finishCandidateAdd()')).toEqual({ state: 'refused', reason: 'compromised-device-admission' })
  expect(await run(page, 'M.candidateAddSnapshot()')).toMatchObject({ registrations: 0 })
  await run(page, 'M.forgetGuest()')
})
test('candidate Add retains the shared gate through actual witnessed Add settlement', async ({ context }) => {
  const { page, witness } = await enrolled(context)
  await run(page, "M.candidateKeeperHold('pending')")
  await run(page, 'M.pauseCandidatePackages(); M.beginCandidateAdd()')
  await expect.poll(async () => (await run(page, 'M.candidateAddSnapshot()')).registrations).toBe(1)
  const before = witness.advances
  let release!: () => void
  witness.advancePause = new Promise<void>(resolve => { release = resolve })
  await run(page, 'M.releaseCandidatePackages()')
  await expect.poll(() => witness.advances).toBeGreaterThan(before)
  const holding = page.evaluate(() => (window as any).M.holdKeeperDevice())
  await expect.poll(() => page.evaluate(async () => (await navigator.locks.query()).pending?.some(lock => lock.name?.startsWith('kithmoot.vmls-grant-install.') && lock.mode === 'exclusive'))).toBe(true)
  expect(await run(page, 'M.candidateAddSnapshot()')).toMatchObject({ result: undefined })
  release(); witness.advancePause = undefined
  await holding
  await run(page, 'M.releaseHeldKeeperDevice()')
  expect(await run(page, 'M.finishCandidateAdd()')).toBe('active')
  await run(page, 'M.forgetGuest()')
})
test('candidate Add invalidated while waiting has no package registration or room mutation', async ({ context }) => {
  const { page } = await enrolled(context)
  await run(page, "M.candidateKeeperHold('pending'); M.holdKeeperDevice()")
  const before = await run(page, 'M.read()')
  await run(page, 'M.beginCandidateAdd()')
  await expect.poll(() => page.evaluate(async () => (await navigator.locks.query()).pending?.some(lock => lock.name?.startsWith('kithmoot.vmls-grant-install.') && lock.mode === 'shared'))).toBe(true)
  await run(page, 'M.invalidateCandidateAdd(); M.releaseHeldKeeperDevice()')
  expect(await run(page, 'M.finishCandidateAdd()')).toMatchObject({ state: 'pending', reason: 'stale' })
  expect(await run(page, 'M.candidateAddSnapshot()')).toMatchObject({ registrations: 0 })
  expect(await run(page, 'M.read()')).toEqual(before)
  await run(page, 'M.forgetGuest()')
})

test('both keeper withdrawal paths wait outside an exclusive device hold and then share exact tombstone settlement', async ({ context }) => {
  const { page } = await enrolled(context)
  await run(page, 'M.addGuest(false, undefined, false, true)'); await run(page, 'M.receiveKeeperRequest()')
  await run(page, 'M.decideKeeperRequest()'); await run(page, 'M.holdKeeperDevice()')
  const keys = [await run(page, "M.beginKeeperWithdrawal('room')"), await run(page, "M.beginKeeperWithdrawal('requested')")]
  await expect.poll(() => page.evaluate(async () => (await navigator.locks.query()).pending?.filter(lock => lock.name?.startsWith('kithmoot.vmls-grant-install.') && lock.mode === 'shared').length)).toBe(2)
  expect(await run(page, 'M.keeperWithdrawalSnapshot()')).toMatchObject({ publications: [], records: [{ state: 'active' }] })
  await run(page, 'M.releaseHeldKeeperDevice()')
  for (const key of keys) expect(await page.evaluate(key => (window as any).M.finishKeeperWithdrawal(key), key)).toEqual({ state: 'revoked', result: 'revoked' })
  expect(await run(page, 'M.keeperWithdrawalSnapshot()')).toMatchObject({ publications: [expect.any(String)], records: [{ state: 'revoked' }] })
  await run(page, 'M.forgetGuest()')
})
for (const kind of ['room', 'requested']) for (const refused of [false, true]) test(`keeper ${kind} withdrawal holds completion until ${refused ? 'uncertain' : 'confirmed'} publication actually settles`, async ({ context }) => {
  const { page } = await enrolled(context)
  await run(page, 'M.addGuest(false, undefined, false, true)'); await run(page, 'M.receiveKeeperRequest()')
  await run(page, 'M.decideKeeperRequest()')
  await page.evaluate(refused => (window as any).M.pauseKeeperWithdrawals(refused), refused)
  const key = await page.evaluate(kind => (window as any).M.beginKeeperWithdrawal(kind), kind)
  await expect.poll(async () => (await run(page, 'M.keeperWithdrawalSnapshot()')).publications.length).toBe(1)
  await run(page, 'M.beginKeeperCompletion()')
  await expect.poll(() => page.evaluate(async () => (await navigator.locks.query()).pending?.some(lock => lock.name?.startsWith('kithmoot.vmls-grant-install.') && lock.mode === 'exclusive'))).toBe(true)
  expect(await run(page, 'M.completionStatus()')).toBeUndefined()
  expect(await run(page, 'M.keeperWithdrawalSnapshot()')).toMatchObject({ records: [{ state: 'revoking' }] })
  await run(page, 'M.resumeKeeperWithdrawals()')
  expect(await page.evaluate(key => (window as any).M.finishKeeperWithdrawal(key), key)).toMatchObject(refused ? { error: 'fixture uncertain withdrawal' } : { state: 'revoked', result: 'revoked' })
  expect(await run(page, 'M.finishKeeperCompletion()')).toMatchObject({ error: expect.stringContaining('still pending') })
  expect(await run(page, 'M.keeperWithdrawalSnapshot()')).toMatchObject({ records: [{ state: refused ? 'revoking' : 'revoked' }] })
  expect(await run(page, 'M.keeperApprovals(true)')).toMatchObject({ value: [{ state: 'approved' }] })
  await run(page, 'M.forgetGuest()')
})
test('keeper completion holds queued installs through actual terminal witness settlement', async ({ context }) => {
  const { page, witness } = await enrolled(context)
  await run(page, 'M.addGuest(false, undefined, false, true)'); await run(page, 'M.receiveKeeperRequest()')
  await run(page, 'M.approveKeeperRequest()'); await run(page, 'M.applyKeeperRemoval()')
  expect(await run(page, 'M.settleKeeperRemovalJournal()')).toMatchObject({ state: 'active', value: { membership: { mls: 'Committed' } } })
  let release!: () => void
  const before = witness.advances
  witness.advancePause = new Promise<void>(resolve => { release = resolve })
  await run(page, 'M.beginKeeperCompletion()')
  await expect.poll(async () => ({ advanced: witness.advances > before, status: await run(page, 'M.completionStatus()') })).toEqual({ advanced: true, status: undefined })
  await run(page, "M.beginKeeperInstall('', false)")
  await expect.poll(() => page.evaluate(async () => (await navigator.locks.query()).pending?.some(lock => lock.name?.startsWith('kithmoot.vmls-grant-install.') && lock.mode === 'shared'))).toBe(true)
  release(); witness.advancePause = undefined
  expect(await run(page, 'M.finishKeeperCompletion()')).toMatchObject({ result: { state: 'active', value: { state: 'done' } } })
  expect(await run(page, 'M.finishKeeperInstall()')).toMatchObject({ error: expect.stringContaining('retained keeper revocation hold') })
  await run(page, 'M.forgetGuest()')
})
test('keeper completion releases its preliminary persona read before waiting and rejects changed retained approval', async ({ context }) => {
  const { page } = await enrolled(context)
  await run(page, 'M.addGuest(false, undefined, false, true)'); await run(page, 'M.receiveKeeperRequest()')
  await run(page, 'M.approveKeeperRequest()'); await run(page, 'M.applyKeeperRemoval()')
  expect(await run(page, 'M.settleKeeperRemovalJournal()')).toMatchObject({ state: 'active', value: { membership: { mls: 'Committed' } } })
  await run(page, 'M.holdKeeperDevice()'); await run(page, 'M.beginKeeperCompletion()')
  await expect.poll(() => page.evaluate(async () => (await navigator.locks.query()).pending?.some(lock => lock.name?.startsWith('kithmoot.vmls-grant-install.') && lock.mode === 'exclusive'))).toBe(true)
  expect(await run(page, 'M.deferKeeperRequest()')).toMatchObject({ state: 'active', value: [{ state: 'approved' }] })
  await run(page, 'M.releaseHeldKeeperDevice()')
  expect(await run(page, 'M.finishKeeperCompletion()')).toMatchObject({ error: expect.stringContaining('request changed while waiting') })
  expect(await run(page, 'M.keeperApprovals(true)')).toMatchObject({ state: 'active', value: [{ state: 'approved' }] })
  expect(await run(page, "M.keeperInstallAttempt('new')")).toMatchObject({ error: expect.stringContaining('retained keeper revocation hold'), signed: 0, writes: 0, published: 0 })
  await run(page, 'M.forgetGuest()')
})
test('keeper acceptance retains failed exact withdrawal across restart and expiry while Remove commits independently', async ({ context }) => {
  const { page } = await enrolled(context)
  expect(await run(page, 'M.addGuest(false, undefined, false, true)')).toBe('active')
  await run(page, 'M.receiveKeeperRequest(false, true, 60)')
  expect(await run(page, 'M.unapprovedKeeperRemoval()')).toEqual({ state: 'refused', reason: 'unapproved-request' })
  expect(await run(page, 'M.keeperWithdrawalAttempts()')).toEqual([])
  await run(page, 'M.failKeeperWithdrawal(true)')
  expect(await run(page, 'M.approveKeeperRequest()')).toMatchObject({ state: 'approved', rooms: [{ state: 'pending' }], grants: [{ state: 'pending', failure: 'fixture box withdrawal refused' }] })
  expect(await run(page, 'M.send()')).toEqual({ state: 'refused', reason: 'compromised-removal' })
  expect(await run(page, 'M.applyKeeperRemoval()')).toMatchObject({ state: 'active' })
  await run(page, 'M.restart(); M.advance(61); M.failKeeperWithdrawal(false)')
  expect(await run(page, 'M.continueKeeperRequest()')).toMatchObject({ state: 'done', rooms: [{ state: 'committed' }], grants: [{ state: 'revoked' }] })
  const attempts = await run(page, 'M.keeperWithdrawalAttempts()')
  expect(attempts).toHaveLength(2); expect(attempts[1]).toBe(attempts[0])
  expect(await run(page, 'M.send()')).toMatchObject({ state: 'active' })
  await run(page, 'M.forgetGuest()')
})
test('keeper acceptance withdraws grants immediately when MLS Remove fails and retains the compromised hold for retry', async ({ context }) => {
  const { page } = await enrolled(context)
  await run(page, 'M.addGuest(false, undefined, false, true)'); await run(page, 'M.receiveKeeperRequest()')
  expect(await run(page, 'M.approveKeeperRequest(true)')).toMatchObject({ state: 'approved', rooms: [{ state: 'pending', failure: 'RemoveFailed' }], grants: [{ state: 'revoked' }] })
  expect(await run(page, 'M.send()')).toEqual({ state: 'refused', reason: 'compromised-removal' })
  expect(await run(page, 'M.continueKeeperRequest()')).toMatchObject({ state: 'approved', rooms: [{ state: 'pending' }], grants: [{ state: 'revoked' }] })
  await run(page, 'M.applyKeeperRemoval()')
  expect(await run(page, 'M.continueKeeperRequest()')).toMatchObject({ state: 'done', rooms: [{ state: 'committed' }], grants: [{ state: 'revoked' }] })
  expect(await run(page, 'M.keeperWithdrawalAttempts()')).toHaveLength(1)
  await run(page, 'M.forgetGuest()')
})
test('dual-clock lapse preserves the compromised hold until real MLS commit without publishing or fabricating engine Revoked', async ({ context }) => {
  const { page } = await enrolled(context)
  await run(page, 'M.addGuest(false, undefined, false, true)'); await run(page, 'M.receiveKeeperRequest()')
  await run(page, 'M.shortenKeeperGrant(60, true)'); await run(page, 'M.addSecondKeeperGrant()')
  expect(await run(page, 'M.decideKeeperRequest()')).toMatchObject({ state: 'active', value: { state: 'approved' } })
  await run(page, 'M.advance(60)')
  const route = pairingFixture(new Uint8Array(32).fill(76)).route
  const lapsed = await page.evaluate(route => (window as any).M.lapseKeeperRequest(route), route)
  expect(lapsed).toMatchObject({ result: { state: 'active', value: { grantOutcomes: [{ outcome: 'no-live' }] } },
    calls: ['/vmls/v1/capabilities', '/vmls/v1/fetch', '/vmls/v1/capabilities'] })
  const first = await run(page, 'M.continueKeeperRequest()')
  expect(first).toMatchObject({ state: 'approved', rooms: [{ state: 'pending' }] })
  expect(first.grants).toEqual(expect.arrayContaining([expect.objectContaining({ state: 'no-live' }), expect.objectContaining({ state: 'revoked' })]))
  expect(await run(page, 'M.send()')).toEqual({ state: 'refused', reason: 'compromised-removal' })
  expect(await run(page, 'M.keeperWithdrawalAttempts()')).toHaveLength(1)
  expect(await run(page, 'M.applyKeeperRemoval()')).toMatchObject({ state: 'active' })
  await run(page, 'M.restart()')
  const done = await run(page, 'M.continueKeeperRequest()')
  expect(done).toMatchObject({ state: 'approved', completion: 'awaiting-grant-install-hold', rooms: [{ state: 'committed' }] })
  expect(done.grants).toEqual(expect.arrayContaining([expect.objectContaining({ state: 'no-live' }), expect.objectContaining({ state: 'revoked' })]))
  expect(await run(page, 'M.membership()')).toMatchObject({ value: [{ mls: 'Committed', grants: [{ state: { type: 'Pending' } }] }] })
  expect(await run(page, 'M.keeperWithdrawalAttempts()')).toHaveLength(1)
  expect(await run(page, 'M.send()')).toEqual({ state: 'refused', reason: 'compromised-removal' })
  await run(page, 'M.forgetGuest()')
})
for (const mode of ['behind', 'refused'] as const) test(`keeper lapse holds with ${mode} box-clock evidence`, async ({ context }) => {
  const { page } = await enrolled(context)
  await run(page, 'M.addGuest(false, undefined, false, true)'); await run(page, 'M.receiveKeeperRequest()')
  await run(page, 'M.shortenKeeperGrant()')
  expect(await run(page, 'M.decideKeeperRequest()')).toMatchObject({ state: 'active' })
  await run(page, 'M.advance(60)')
  const route = pairingFixture(new Uint8Array(32).fill(76)).route
  const result = await page.evaluate(({ route, mode }) => (window as any).M.lapseKeeperRequest(route, mode), { route, mode })
  if (mode === 'behind') expect(result.error).toContain('Both authenticated clocks')
  else expect(result).toMatchObject({ result: { state: 'held' } })
  expect(await run(page, 'M.keeperApprovals()')).toMatchObject({ value: [{ state: 'approved' }] })
  expect(await run(page, 'M.send()')).toEqual({ state: 'refused', reason: 'compromised-removal' })
  expect(await run(page, 'M.keeperWithdrawalAttempts()')).toEqual([])
  await run(page, 'M.forgetGuest()')
})
test('mixed unavailable and revoked grants preserve the compromised hold until real MLS commit and survive restored pairing', async ({ context }) => {
  const { page } = await enrolled(context)
  await run(page, 'M.addGuest(false, undefined, false, true)'); await run(page, 'M.receiveKeeperRequest()')
  await run(page, 'M.addSecondKeeperGrant()'); await run(page, 'M.forgetKeeperRoute()')
  const first = await run(page, 'M.approveKeeperRequest()')
  expect(first.state).toBe('approved'); expect(first.rooms).toMatchObject([{ state: 'pending' }])
  expect(first.grants).toEqual(expect.arrayContaining([expect.objectContaining({ state: 'unavailable', access: 'unconfirmed' }), expect.objectContaining({ state: 'revoked' })]))
  expect(await run(page, 'M.keeperWithdrawalAttempts()')).toHaveLength(1)
  expect(await run(page, 'M.send()')).toEqual({ state: 'refused', reason: 'compromised-removal' })
  expect(await run(page, 'M.applyKeeperRemoval()')).toMatchObject({ state: 'active' })
  await run(page, 'M.restart(); M.forgetKeeperRoute(false)')
  const roster = await run(page, 'M.members()')
  expect(roster, JSON.stringify(roster)).toMatchObject({ state: 'active', value: [{ own: true }] })
  const completed = await run(page, 'M.continueKeeperRequest()')
  expect(completed.state, JSON.stringify(completed)).toBe('done'); expect(completed.rooms).toMatchObject([{ state: 'committed' }])
  expect(completed.grants).toEqual(expect.arrayContaining([expect.objectContaining({ state: 'unavailable', access: 'unconfirmed' }), expect.objectContaining({ state: 'revoked' })]))
  expect(await run(page, 'M.membership()')).toMatchObject({ value: [{ mls: 'Committed', grants: [{ state: { type: 'Pending' } }] }] })
  expect(await run(page, 'M.keeperWithdrawalAttempts()')).toHaveLength(1)
  expect(await run(page, 'M.send()')).toMatchObject({ state: 'active' })
  await run(page, 'M.forgetGuest()')
})
test('keeper ledger-only acceptance withdraws without grace or a fabricated MLS Remove', async ({ context }) => {
  const { page } = await enrolled(context)
  await run(page, 'M.addGuest(false, undefined, false, true)')
  await run(page, 'M.beginGuestRemoval()'); await run(page, 'M.applyGuestRemoval()'); await run(page, 'M.driveGuestRemoval()')
  await run(page, 'M.receiveKeeperRequest(false, true)')
  expect(await run(page, 'M.approveKeeperRequest()')).toMatchObject({ state: 'done', rooms: [], grants: [{ state: 'revoked' }] })
  expect(await run(page, 'M.keeperWithdrawalAttempts()')).toHaveLength(1)
  await run(page, 'M.forgetGuest()')
})
test('keeper consent records actual room scope and holds sends before any Remove journal, including after request expiry', async ({ context }) => {
  const { page } = await enrolled(context)
  expect(await run(page, 'M.addGuest(false, undefined, false, true)')).toBe('active')
  expect(await run(page, 'M.receiveKeeperRequest(false, true, 60)')).toMatchObject({ state: 'active' })
  expect(await run(page, 'M.keeperDecisionPlan()')).toMatchObject({ state: 'active', value: { rooms: [{ name: 'Witnessed room', action: 'remove' }], grants: [{ rooms: [] }] } })
  expect(await run(page, 'M.decideKeeperRequest()')).toMatchObject({ state: 'active', value: { state: 'approved', approval: { rooms: [{ action: 'remove' }] } } })
  expect(await run(page, 'M.send()')).toEqual({ state: 'refused', reason: 'compromised-removal' })
  await run(page, 'M.advance(61)'); await run(page, 'M.keeperRequests()')
  expect(await run(page, 'M.send()')).toEqual({ state: 'refused', reason: 'compromised-removal' })
  expect(await run(page, 'M.beginGuestRemoval()')).toMatchObject({ state: 'active' })
  expect(await run(page, 'M.applyGuestRemoval()')).toMatchObject({ state: 'active' })
  expect(await run(page, 'M.driveGuestRemoval()')).toMatchObject({ state: 'active', value: { membership: { mls: 'Committed' } } })
  expect(await run(page, 'M.send()')).toMatchObject({ state: 'active' })
  await run(page, 'M.forgetGuest()')
})
test('keeper dismissal has no send hold or automatic membership change', async ({ context }) => {
  const { page } = await enrolled(context)
  expect(await run(page, 'M.addGuest(false, undefined, false, true)')).toBe('active')
  await run(page, 'M.receiveKeeperRequest()')
  expect(await run(page, 'M.decideKeeperRequest(false)')).toMatchObject({ state: 'active', value: { state: 'dismissed' } })
  expect(await run(page, 'M.send()')).toMatchObject({ state: 'active' })
  await run(page, 'M.forgetGuest()')
})
test('keeper pending Later survives a witnessed restart, blocks stale approval and returns after an hour', async ({ context }) => {
  const { page } = await enrolled(context)
  await run(page, 'M.addGuest(false, undefined, false, true)'); await run(page, 'M.receiveKeeperRequest()')
  const review = await run(page, 'M.keeperDecisionPlan()')
  expect(review).toMatchObject({ state: 'active' })
  expect(await run(page, 'M.deferKeeperRequest()')).toMatchObject({ state: 'active', value: [{ state: 'pending' }] })
  await run(page, 'M.restart()')
  expect(await run(page, 'M.keeperRequests()')).toMatchObject({ value: { prompts: [], deferred: [{ prompt: { state: 'pending' } }] } })
  await expect(run(page, 'M.decideKeeperRequest()')).rejects.toThrow('deferred')
  expect(await run(page, 'M.send()')).toMatchObject({ state: 'active' })
  expect(await run(page, 'M.keeperWithdrawalAttempts()')).toEqual([])
  await run(page, 'M.advance(3600)')
  await expect(page.evaluate(plan => (window as any).M.decideReviewedKeeperRequest(plan), review.value)).rejects.toThrow('current keeper account')
  expect(await run(page, 'M.keeperDecisionPlan()')).toMatchObject({ state: 'active', value: { prompt: { state: 'pending' } } })
  await run(page, 'M.forgetGuest()')
})
test('keeper Later permanently invalidates the pre-deferral review even after the hour in the same account', async ({ context }) => {
  const { page } = await enrolled(context)
  await run(page, 'M.addGuest(false, undefined, false, true)'); await run(page, 'M.receiveKeeperRequest()')
  const review = await run(page, 'M.keeperDecisionPlan()')
  expect(review).toMatchObject({ state: 'active' })
  await run(page, 'M.deferKeeperRequest()'); await run(page, 'M.advance(3600)')
  await expect(page.evaluate(plan => (window as any).M.decideReviewedKeeperRequest(plan), review.value)).rejects.toThrow('authority changed')
  expect(await run(page, 'M.decideKeeperRequest()')).toMatchObject({ state: 'active', value: { state: 'approved' } })
  expect(await run(page, 'M.keeperWithdrawalAttempts()')).toEqual([])
  await run(page, 'M.forgetGuest()')
})
test('keeper approved Later retains witnessed consent and the compromised hold after restart and request expiry', async ({ context }) => {
  const { page } = await enrolled(context)
  await run(page, 'M.addGuest(false, undefined, false, true)'); await run(page, 'M.receiveKeeperRequest(false, true, 60)')
  await run(page, 'M.decideKeeperRequest()')
  expect(await run(page, 'M.deferKeeperRequest()')).toMatchObject({ state: 'active', value: [{ state: 'approved' }] })
  await run(page, 'M.restart(); M.advance(61)')
  expect(await run(page, 'M.keeperApprovals()')).toMatchObject({ value: [] })
  expect(await run(page, 'M.keeperApprovals(true)')).toMatchObject({ value: [{ state: 'approved' }] })
  expect(await run(page, 'M.send()')).toEqual({ state: 'refused', reason: 'compromised-removal' })
  expect(await run(page, 'M.keeperWithdrawalAttempts()')).toEqual([])
  await run(page, 'M.advance(3539)')
  expect(await run(page, 'M.keeperApprovals()')).toMatchObject({ value: [{ state: 'approved' }] })
  expect(await run(page, 'M.send()')).toEqual({ state: 'refused', reason: 'compromised-removal' })
  await run(page, 'M.forgetGuest()')
})
test('keeper inbox checks the genuine witnessed roster and retains prompts across restart', async ({ context }) => {
  const { page } = await enrolled(context)
  expect(await run(page, 'M.addGuest(false, undefined, false, true)')).toBe('active')
  expect(await run(page, 'M.receiveKeeperRequest(true, true)')).toMatchObject({ state: 'active', value: { prompts: [] } })
  expect(await run(page, 'M.receiveKeeperRequest(true)')).toMatchObject({ state: 'active', value: { prompts: [] } })
  const correct = await run(page, 'M.receiveKeeperRequest()')
  expect(correct).toMatchObject({ state: 'active', value: { prompts: [{ conflict: false, grants: [{ state: 'active', rooms: [{ name: 'Witnessed room' }] }], prompt: { state: 'pending' } }] } })
  await run(page, 'M.restart()')
  expect(await run(page, 'M.keeperRequests()')).toEqual(correct)
  await run(page, 'M.forgetGuest()')
})
test('keeper inbox can review a signed ledger-only grant after the device has no room left', async ({ context }) => {
  const { page } = await enrolled(context)
  expect(await run(page, 'M.addGuest(false, undefined, false, true)')).toBe('active')
  expect(await run(page, 'M.beginGuestRemoval()')).toMatchObject({ state: 'active' })
  expect(await run(page, 'M.applyGuestRemoval()')).toMatchObject({ state: 'active' })
  expect(await run(page, 'M.driveGuestRemoval()')).toMatchObject({ state: 'active', value: { membership: { mls: 'Committed' } } })
  const result = await run(page, 'M.receiveKeeperRequest(false, true)')
  expect(result).toMatchObject({ state: 'active', value: { prompts: [{ grants: [{ state: 'active', rooms: [] }], prompt: { state: 'pending' } }] } })
  await run(page, 'M.restart()')
  expect(await run(page, 'M.keeperRequests()')).toEqual(result)
  await run(page, 'M.forgetGuest()')
})
test('typed creation, idempotent send and rename persist with the session', async ({ context }) => {
  const { page } = await enrolled(context)
  const keepers = await run(page, 'M.keeperIdentities()')
  expect(await run(page, 'M.revocationAuthority()')).toMatchObject({ state: 'active', value: { name: 'Witnessed room', keeper: keepers.created } })
  expect(await run(page, 'M.read()')).toMatchObject({ state: 'active', value: { name: 'Witnessed room', history: [], generation: '1' } })
  expect(await run(page, 'M.send()')).toMatchObject({ state: 'active' })
  const before = await run(page, 'M.read()')
  expect(before.value.history).toHaveLength(1)
  expect(await run(page, 'M.send()')).toMatchObject({ state: 'active', value: { outcome: { type: 'Duplicate' } } })
  expect(await run(page, 'M.read()')).toEqual(before)
  expect(await run(page, `M.send('${'01'.repeat(32)}', 'substituted')`)).toEqual({ state: 'refused', reason: 'replay' })
  expect(await run(page, 'M.rename()')).toEqual({ state: 'active', value: undefined })
  await run(page, 'M.restart()'); await run(page, 'M.discover()')
  expect(await run(page, 'M.read()')).toMatchObject({ state: 'active', value: { name: 'New name', generation: '2' } })
})
test('typed Update creates a witnessed commit outbox', async ({ context }) => {
  const { page } = await enrolled(context)
  const result = await run(page, 'M.update()')
  expect(result.state).toBe('active')
  expect(result.value.outbound.some((r: any) => r.destination.type === 'CommitSlot')).toBe(true)
  await run(page, 'M.restart()')
  const room = await run(page, 'M.read()')
  expect(room.value.outbox).toEqual(result.value.outbound)
  expect(room.value.generation).toBe('2')
})
for (const action of ['send', 'parallel', 'replace', 'revoke', 'withdraw', 'account', 'expire', 'invalidate'] as const) test(`pending Update refuses after ${action}`, async ({ context }) => {
  const { page } = await enrolled(context)
  const answer = await run(page, `M.race('${action}')`)
  expect(answer.result.state).not.toBe('active')
  if (action === 'send' || action === 'parallel') expect(answer.nested.state).toBe('active')
})
test('a concurrent room-only rename is preserved by Update', async ({ context }) => {
  const { page } = await enrolled(context)
  expect(await run(page, "M.race('rename')")).toMatchObject({ result: { state: 'active' }, nested: { state: 'active' } })
  expect(await run(page, 'M.read()')).toMatchObject({ state: 'active', value: { name: 'Concurrent name', generation: '2' } })
})
for (const operation of ['create', 'send', 'update'] as const) for (const at of ['stage', 'promotion', 'stale-close'] as const) test(`${operation} recovers atomic state after ${at}`, async ({ context }) => {
  const { page } = await enrolled(context, operation !== 'create')
  const r = await run(page, `M.fault('${operation}', '${at}')`)
  expect(r.injected).toBe(true)
  expect(r.result?.state).not.toBe('active')
  await run(page, 'M.restart()'); await run(page, 'M.discover()')
  const reopened = await run(page, 'M.read()')
  expect(reopened.state).toBe('active')
  expect(reopened.value.generation).toBe(operation === 'create' ? '1' : '2')
  expect(reopened.value.history.length).toBe(operation === 'send' ? 1 : 0)
  if (operation === 'send') expect(await run(page, 'M.send()')).toMatchObject({ state: 'active', value: { outcome: { type: 'Duplicate' } } })
})
test('an Update expiring during shutdown releases no result but retains its committed outbox', async ({ context }) => {
  const { page } = await enrolled(context)
  expect(await run(page, "M.fault('update', 'expiry-close')")).toMatchObject({ injected: true, result: { state: 'pending' } })
  await run(page, 'M.restart()')
  expect(await run(page, 'M.read()')).toMatchObject({ state: 'active', value: { generation: '2' } })
})
test('Update binding expiry during cleanup withholds effects before the RPC deadline', async ({ context }) => {
  const { page } = await enrolled(context)
  expect(await run(page, "M.fault('update', 'binding-expiry-close')")).toMatchObject({ injected: true, result: { state: 'pending', reason: 'stale' } })
})
for (const operation of ['create', 'update'] as const) for (const end of ['invalidate', 'expiry'] as const) test(`never-resolving ${operation} consent is bounded by ${end}`, async ({ context }) => {
  const { page } = await enrolled(context, operation !== 'create')
  expect(await run(page, `M.pendingNever('${operation}', '${end}')`)).toMatchObject({ state: 'pending' })
  expect((await run(page, 'M.local()')).generation).toBe(operation === 'create' ? null : '1')
})
test('denied creation stores no session; offline operations release nothing', async ({ context }) => {
  const { page, witness } = await enrolled(context, false)
  expect(await run(page, "M.create('deny')")).toEqual({ state: 'refused', reason: 'denied' })
  expect((await run(page, 'M.local()')).generation).toBeNull()
  expect(await run(page, 'M.create()')).toMatchObject({ state: 'active' })
  witness.offline = true
  expect(await run(page, 'M.send()')).toEqual({ state: 'refused', reason: 'witness-pending' })
  expect((await run(page, 'M.local()')).generation).toBe('1')
})
test('history limits abort the ratchet and missing metadata fences', async ({ context }) => {
  const { page } = await enrolled(context)
  expect(await run(page, 'M.historyFull()')).toBe('active')
  const before = await run(page, 'M.local()')
  expect(await run(page, 'M.send()')).toEqual({ state: 'refused', reason: 'history-full' })
  expect(await run(page, 'M.local()')).toEqual(before)
  await run(page, 'M.damageRoom()')
  expect(await run(page, 'M.read()')).toMatchObject({ state: 'fenced' })
})
test('accepted remote plaintext is witnessed with the receive ratchet and duplicate records add no history', async ({ context }) => {
  const { page } = await enrolled(context)
  expect(await run(page, 'M.addGuest()')).toBe('active')
  const first = await run(page, 'M.receive()')
  expect(first).toMatchObject({ state: 'active', value: { outcome: { type: 'Accepted' }, ack: { type: 'AfterCommitAck' } } })
  expect(first.value.events.find((e: any) => e.type === 'Message').body).toBeDefined()
  const before = await run(page, 'M.read()')
  expect(before.value.history).toHaveLength(1)
  expect(await run(page, 'M.receive()')).toMatchObject({ state: 'active', value: { outcome: { type: 'Duplicate' } } })
  expect(await run(page, 'M.read()')).toEqual(before)
  await run(page, 'M.forgetGuest()')
})
test('a compromised-device removal is journalled, blocks sends and resumes only after witnessed Remove readback', async ({ context }) => {
  const { page } = await enrolled(context)
  expect(await run(page, 'M.addGuest()')).toBe('active')
  expect(await run(page, 'M.members()')).toMatchObject({ state: 'active', value: [
    { own: true, pending: false, leafId: expect.stringMatching(/^[0-9a-f]{64}$/), identity: expect.stringMatching(/^[0-9a-f]{64}$/), device: expect.stringMatching(/^[0-9a-f]{64}$/), homeBox: expect.stringMatching(/^[0-9a-f]{64}$/) },
    { own: false, pending: false, leafId: expect.stringMatching(/^[0-9a-f]{64}$/), identity: expect.stringMatching(/^[0-9a-f]{64}$/), device: expect.stringMatching(/^[0-9a-f]{64}$/), homeBox: expect.stringMatching(/^[0-9a-f]{64}$/) },
  ] })
  const opened = await run(page, 'M.beginGuestRemoval()')
  expect(opened).toMatchObject({ state: 'active', value: { compromised: true, attempts: 0, mls: 'Pending', claim: 'ComponentsOnly', next: { type: 'Propose' } } })
  expect(await run(page, 'M.beginGuestRemoval()')).toEqual(opened)
  expect(await run(page, `M.send('${'04'.repeat(32)}', 'held')`)).toEqual({ state: 'refused', reason: 'compromised-removal' })
  expect(await run(page, 'M.applyGuestRemoval()')).toMatchObject({ state: 'active', value: { outcome: { type: 'Accepted' } } })
  const committed = await run(page, 'M.driveGuestRemoval()')
  expect(committed).toMatchObject({ state: 'active', value: { membership: { attempts: 1, mls: 'Committed', claim: 'RemoveApplied', next: { type: 'Done' } } } })
  expect(await run(page, 'M.membership()')).toMatchObject({ state: 'active', value: [{ operation: '03'.repeat(32), mls: 'Committed' }] })
  expect(await run(page, `M.send('${'04'.repeat(32)}', 'released')`)).toMatchObject({ state: 'active' })
  await run(page, 'M.forgetGuest()')
})
test('membership journalling refuses a roster that changed after review', async ({ context }) => {
  const { page } = await enrolled(context)
  expect(await run(page, 'M.addGuest()')).toBe('active')
  expect(await run(page, 'M.beginGuestRemovalWithStaleRoster()')).toEqual({ state: 'refused', reason: 'replay' })
  expect(await run(page, 'M.membership()')).toMatchObject({ state: 'active', value: [] })
  await run(page, 'M.forgetGuest()')
})
test('member request metadata and the requested transition are witnessed and bound to the engine grant', async ({ context }) => {
  const { page } = await enrolled(context, false)
  await joinedWithMemberDevice(page)
  const opened = await run(page, 'M.beginJoinedMemberRequest()')
  expect(opened).toMatchObject({ state: 'active', value: { request: { sessions: [expect.stringMatching(/^[0-9a-f]{64}$/)], boxes: [expect.stringMatching(/^[0-9a-f]{64}$/)] },
    grants: [{ grant: { keeper: false }, state: { type: 'NotAuthorised', requested: false } }] } })
  await run(page, 'M.restartJoin()')
  expect(await run(page, 'M.joinMembership()')).toMatchObject({ state: 'active', value: [{ operation: '07'.repeat(32),
    grants: [{ state: { type: 'NotAuthorised', requested: false } }] }] })
  expect(await run(page, 'M.markJoinedMemberRequest()')).toMatchObject({ state: 'active', value: {
    grants: [{ state: { type: 'NotAuthorised', requested: true } }] } })
  await run(page, 'M.forgetGuest()')
})
test('a witnessed same-person roster device remains in the sealed standalone outbox after restart', async ({ context }) => {
  const { page } = await enrolled(context, false)
  await joinedWithMemberDevice(page)
  const keepers = await run(page, 'M.keeperIdentities()')
  expect(await run(page, 'M.joinMembers()')).toMatchObject({ state: 'active' })
  const before = await run(page, 'M.standaloneRequests()')
  expect(before).toMatchObject({ state: 'active', value: [{
    operation: expect.stringMatching(/^[0-9a-f]{64}$/), sender: expect.stringMatching(/^[0-9a-f]{64}$/), keeper: keepers.joined,
    device: expect.stringMatching(/^[0-9a-f]{64}$/), sessions: [expect.stringMatching(/^[0-9a-f]{64}$/)],
    boxes: [expect.stringMatching(/^[0-9a-f]{64}$/)], createdAt: expect.any(Number), sentAt: null,
  }] })
  await run(page, 'M.restartJoin()')
  expect(await run(page, 'M.standaloneRequests()')).toEqual(before)
  await run(page, 'M.forgetGuest()')
})
test('member requests require the retained keeper and the requesting persona own the reviewed target', async ({ context }) => {
  const { page } = await enrolled(context, false)
  await joinedWithMemberDevice(page)
  for (const mode of ['wrong-device', 'wrong-keeper', 'wrong-box', 'other-person']) {
    expect(await run(page, `M.beginJoinedMemberRequest('${mode}')`)).toEqual({ state: 'refused', reason: 'malformed' })
  }
  expect(await run(page, 'M.joinMembership()')).toMatchObject({ state: 'active', value: [] })
  expect(await run(page, 'M.joinMembers()')).toMatchObject({ state: 'active', value: expect.arrayContaining([
    expect.objectContaining({ leafId: expect.stringMatching(/^[0-9a-f]{64}$/) }),
  ]) })
  await run(page, 'M.forgetGuest()')
})
test('member request metadata that no longer matches the room keeper fences the persona', async ({ context }) => {
  const { page } = await enrolled(context, false)
  await joinedWithMemberDevice(page)
  expect(await run(page, 'M.beginJoinedMemberRequest()')).toMatchObject({ state: 'active' })
  expect(await run(page, 'M.damageJoinedMemberRequestKeeper()')).toBe('active')
  expect(await run(page, 'M.joinMembership()')).toMatchObject({ state: 'fenced', reason: 'invalid-vault' })
  await run(page, 'M.forgetGuest()')
})
test('a transient Remove refusal stays pending and is proposed again', async ({ context }) => {
  const { page } = await enrolled(context)
  expect(await run(page, 'M.addGuest()')).toBe('active')
  expect(await run(page, 'M.beginGuestRemoval()')).toMatchObject({ state: 'active' })
  expect(await run(page, "M.driveGuestRemovalFailure('OutboxFull')")).toMatchObject({ state: 'active', value: { membership: { attempts: 0, failure: null, mls: 'Pending', next: { type: 'Propose' } } } })
  expect(await run(page, 'M.applyGuestRemoval()')).toMatchObject({ state: 'active', value: { outcome: { type: 'Accepted' } } })
  expect(await run(page, 'M.driveGuestRemoval()')).toMatchObject({ state: 'active', value: { membership: { mls: 'Committed' } } })
  await run(page, 'M.forgetGuest()')
})
test('a compromised hold permits the own Update needed for removal progress', async ({ context }) => {
  const { page } = await enrolled(context)
  expect(await run(page, 'M.addGuest()')).toBe('active')
  expect(await run(page, 'M.beginGuestRemoval()')).toMatchObject({ state: 'active', value: { compromised: true } })
  expect(await run(page, 'M.update()')).toMatchObject({ state: 'active', value: { outbound: expect.any(Array) } })
  expect(await run(page, `M.send('${'05'.repeat(32)}', 'still held')`)).toEqual({ state: 'refused', reason: 'compromised-removal' })
  await run(page, 'M.forgetGuest()')
})
test('a failed Remove catches up when the target leaves through another applied Remove', async ({ context }) => {
  const { page } = await enrolled(context)
  expect(await run(page, 'M.addGuest()')).toBe('active')
  expect(await run(page, 'M.beginGuestRemoval()')).toMatchObject({ state: 'active' })
  expect(await run(page, 'M.applyGuestRemoval()')).toMatchObject({ state: 'active' })
  expect(await run(page, 'M.markGuestRemovalFailed()')).toBe('active')
  expect(await run(page, 'M.driveGuestRemoval()')).toMatchObject({ state: 'active', value: { membership: { failure: null, mls: 'Committed', next: { type: 'Done' } } } })
  await run(page, 'M.forgetGuest()')
})
test('malformed sealed membership bytes fence the persona', async ({ context }) => {
  const { page } = await enrolled(context)
  expect(await run(page, 'M.addGuest()')).toBe('active')
  expect(await run(page, 'M.beginGuestRemoval()')).toMatchObject({ state: 'active' })
  expect(await run(page, 'M.damageGuestRemovalJournal()')).toBe('active')
  expect(await run(page, 'M.membership()')).toMatchObject({ state: 'fenced', reason: 'invalid-vault' })
  await run(page, 'M.forgetGuest()')
})
for (const at of ['stage', 'promotion', 'stale-close'] as const) test(`remote plaintext survives ${at} without early acknowledgement`, async ({ context }) => {
  const { page } = await enrolled(context)
  await run(page, 'M.addGuest()')
  const result = await run(page, `M.fault('receive', '${at}')`)
  expect(result.injected).toBe(true)
  expect(result.result?.state).not.toBe('active')
  await run(page, 'M.restart()')
  const saved = await run(page, 'M.read()')
  expect(saved.value.history).toHaveLength(1)
  expect(await run(page, 'M.receive()')).toMatchObject({ state: 'active', value: { outcome: { type: 'Duplicate' } } })
  expect(await run(page, 'M.read()')).toEqual(saved)
  await run(page, 'M.forgetGuest()')
})
test('accepted witness reply loss retains history and send idempotency across restart', async ({ context }) => {
  const { page, witness } = await enrolled(context)
  witness.loseAdvance = true
  expect(await run(page, 'M.send()')).toMatchObject({ state: 'pending' })
  await run(page, 'M.restart()')
  expect((await run(page, 'M.read()')).value.history).toHaveLength(1)
  expect(await run(page, 'M.send()')).toMatchObject({ state: 'active', value: { outcome: { type: 'Duplicate' } } })
})

for (const operation of ['create', 'update'] as const) for (const end of ['invalidate', 'expiry'] as const) test(`${operation} cancellation cleans up both operations after free throws on ${end}`, async ({ context }) => {
  const { page } = await enrolled(context, operation !== 'create')
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message))
  const result = await run(page, `M.cancelledCleanup('${operation}', '${end}')`)
  expect(result.freed).toBe(2)
  expect(result.results).toEqual([{ error: 'fixture free failure' }, { state: 'pending', reason: 'stale', refused: false }])
  expect(errors).toEqual([])
})
test('completed creation cleanup failure releases no effects and preserves witnessed state', async ({ context }) => {
  const { page } = await enrolled(context, false)
  expect(await run(page, 'M.completedCleanup()')).toEqual({ error: 'fixture completed free failure' })
  expect((await run(page, 'M.local()')).generation).toBe('1')
  await run(page, 'M.restart()'); await run(page, 'M.discover()')
  expect(await run(page, 'M.read()')).toMatchObject({ state: 'active', value: { generation: '1' } })
})

for (const mode of ['clock-ok', 'clock-server-ahead', 'clock-refused', 'clock-installation', 'clock-account', 'clock-rewind', 'clock-admission-clone', 'clock-admission-account', 'clock-admission-grant']) test(`keeper clock probe with real vault and WASM: ${mode}`, async ({ context }) => {
  const { page } = await enrolled(context, false)
  const result = await page.evaluate(({ route, mode }) => (window as any).M.boxClientScenario(route, mode), { route: pairingFixture(new Uint8Array(32).fill(76)).route, mode })
  if (mode === 'clock-ok' || mode === 'clock-server-ahead') {
    expect(result.evidence).toMatchObject({ installation: '79'.repeat(32), reference: expect.stringMatching(/^[0-9a-f]{64}$/), phoneTime: expect.any(Number), boxTime: expect.any(Number) })
    expect(result.evidence.boxTime - result.evidence.phoneTime).toBe(mode === 'clock-server-ahead' ? 30 * 86400 : 0)
    expect(result.lapsed).toBe(false)
    expect(result.calls.map((c: any) => c.path)).toEqual(['/vmls/v1/capabilities', '/vmls/v1/fetch', '/vmls/v1/capabilities'])
    expect(result.distinctEvents).toBe(3)
  } else if (mode === 'clock-rewind') expect(result.error).toContain('trusted keeper time')
  else if (mode.startsWith('clock-admission-')) { expect(result.error).toContain('no longer current'); expect(result.calls).toHaveLength(3) }
  else {
    expect(result.evidence).toBeNull()
    expect(result.calls).toHaveLength(mode === 'clock-installation' ? 3 : 2)
  }
})

for (const mode of ['routes', 'caps-invalid', 'denied', 'stale-consent', 'late-reply', 'lost-reply', 'bad-receipt', 'cancel-consent', 'timeout-consent']) test(`strict box client with real vault and WASM: ${mode}`, async ({ context }) => {
  const { page } = await enrolled(context, false)
  const result = await page.evaluate(({ route, mode }) => (window as any).M.boxClientScenario(route, mode), { route: pairingFixture(new Uint8Array(32).fill(76)).route, mode })
  if (mode === 'routes') {
    expect(result.results.map((r: any) => r.state)).toEqual(new Array(6).fill('ok'))
    expect(result.calls).toHaveLength(6); expect(result.distinctEvents).toBe(6)
    expect(result.results[0].value.installation).toBe('79'.repeat(32))
  } else if (mode === 'lost-reply') {
    expect(result.results.map((r: any) => r.state)).toEqual(['unavailable', 'ok']); expect(result.distinctEvents).toBe(2)
  } else if (mode === 'bad-receipt') expect(result.results.map((r: any) => r.state)).toEqual(['ok', 'malformed'])
  else if (mode === 'caps-invalid') expect(result.results[0].state).toBe('malformed')
  else if (mode === 'denied') { expect(result.results[0]).toEqual({ state: 'not-signed', reason: 'denied' }); expect(result.calls).toHaveLength(0) }
  else if (mode === 'cancel-consent' || mode === 'timeout-consent') {
    expect(result.results[0].state).toBe('unavailable'); expect(result.calls).toHaveLength(0); expect(result.approved).toEqual([])
  } else { expect(result.results[0].state).toBe('unavailable'); expect(result.calls).toHaveLength(mode === 'stale-consent' ? 0 : 1) }
})

test('typed join survives reload, accepts authenticated Welcome and requires its first Update', async ({ context }) => {
  const { page } = await enrolled(context, false)
  await run(page, 'M.provisionJoin()')
  const joining = await run(page, 'M.typedJoin()')
  expect(joining.state).toBe('active')
  const keepers = await run(page, 'M.keeperIdentities()')
  expect(await run(page, 'M.joinRevocationAuthority()')).toMatchObject({ state: 'active', value: { name: 'Joined room', keeper: keepers.joined } })
  const reopened = await run(page, 'M.recoverJoin()')
  expect(reopened).toMatchObject({ state: 'active', value: { phase: { type: 'PendingJoin' }, name: 'Joined room' } })
  expect(reopened.value.outbox).toEqual(joining.value.outbound)
  expect(await run(page, 'M.sendJoin()')).toEqual({ state: 'refused', reason: 'not-joined' })
  expect(await run(page, 'M.makeJoinWelcome()')).toBe(true)
  expect((await run(page, `M.acceptJoinWelcome('${'00'.repeat(32)}')`)).value.outcome.type).not.toBe('Accepted')
  expect((await run(page, 'M.readJoin()')).value.phase.type).toBe('PendingJoin')
  expect(await run(page, `M.acceptJoinWelcome(undefined, '${'00'.repeat(32)}')`)).toEqual({ state: 'refused', reason: 'wrong-box' })
  expect(await run(page, 'M.acceptJoinWelcome()')).toMatchObject({ state: 'active', value: { outcome: { type: 'Accepted' }, ack: { type: 'AfterCommitAck' } } })
  expect((await run(page, 'M.readJoin()')).value.updateRequired).toBe(true)
  expect(await run(page, 'M.sendJoin()')).toEqual({ state: 'refused', reason: 'update-required' })
  expect((await run(page, 'M.firstJoinUpdate()')).state).toBe('active')
  expect(await run(page, 'M.sendJoin()')).toMatchObject({ state: 'active' })
  expect((await run(page, 'M.recoverJoin()')).value.history).toHaveLength(1)
})
test('a joined session completes UpdateFirst, Update and witnessed Remove in order', async ({ context }) => {
  const { page } = await enrolled(context, false)
  await run(page, 'M.provisionJoin()')
  expect((await run(page, 'M.typedJoin()')).state).toBe('active')
  expect(await run(page, 'M.makeJoinWelcome()')).toBe(true)
  expect(await run(page, 'M.acceptJoinWelcome()')).toMatchObject({ state: 'active', value: { outcome: { type: 'Accepted' } } })

  const opened = await run(page, 'M.beginJoinInviterRemoval()')
  expect(opened).toMatchObject({ state: 'active', value: { compromised: true, attempts: 0, mls: 'Pending', next: { type: 'UpdateFirst' } } })
  expect(await run(page, 'M.driveJoinInviterRemoval()')).toMatchObject({
    state: 'active', value: { outbound: [], membership: { attempts: 0, mls: 'Pending', next: { type: 'UpdateFirst' } } },
  })
  expect((await run(page, 'M.readJoin()')).value.updateRequired).toBe(true)

  expect(await run(page, 'M.firstJoinUpdate()')).toMatchObject({ state: 'active', value: { outcome: { type: 'Accepted' } } })
  expect((await run(page, 'M.readJoin()')).value.updateRequired).toBe(false)

  const removed = await run(page, 'M.applyJoinInviterRemoval()')
  expect(removed).toMatchObject({
    driven: { state: 'active', value: { outbound: [expect.objectContaining({ destination: expect.objectContaining({ type: 'CommitSlot' }) })], membership: { attempts: 1, mls: 'Pending', next: { type: 'Wait' } } } },
    applied: { state: 'active', value: { outcome: { type: 'Accepted' } } },
  })
  expect(await run(page, 'M.driveJoinInviterRemoval()')).toMatchObject({ state: 'active', value: { membership: { attempts: 1, mls: 'Committed', next: { type: 'Done' } } } })
  const finalRoster = await run(page, 'M.joinMembers()')
  expect(finalRoster.state).toBe('active')
  expect(finalRoster.value).toHaveLength(1)
  expect(finalRoster.value[0]).toMatchObject({ own: true, pending: false })
})
for (const mode of ['deny', 'clear', 'replace', 'account', 'invalidate', 'expiry', 'revoke', 'device']) test(`typed join refuses stale authorisation after ${mode}`, async ({ context }) => {
  const { page } = await enrolled(context, false)
  await run(page, 'M.provisionJoin()')
  expect((await run(page, `M.typedJoin('${mode}')`)).state).not.toBe('active')
  expect((await run(page, 'M.local()')).generation).toBeNull()
  if (['clear', 'replace', 'invalidate'].includes(mode)) expect((await run(page, 'M.joinPermissions()')).value.approved).toEqual([])
})
for (const at of ['stage', 'promotion', 'stale-close', 'lost-advance']) for (const welcome of [false, true]) test(`typed ${welcome ? 'Welcome' : 'join'} recovers ${at} without early effects`, async ({ context }) => {
  const { page } = await enrolled(context, false)
  await run(page, 'M.provisionJoin()')
  if (welcome) { await run(page, 'M.typedJoin()'); await run(page, 'M.makeJoinWelcome()') }
  const lost = await run(page, `M.joinFault('${at}', ${welcome})`)
  expect(lost.injected).toBe(true)
  expect(lost.result?.state).not.toBe('active')
  const recovered = await run(page, 'M.recoverJoin()')
  expect(recovered).toMatchObject({ state: 'active', value: { phase: { type: welcome ? 'Active' : 'PendingJoin' }, generation: welcome ? '2' : '1' } })
  if (welcome) expect(recovered.value.updateRequired).toBe(true)
  else expect(recovered.value.outbox[0].destination.type).toBe('Introduction')
})
test('queued typed join cannot miss a child clear before lock acquisition', async ({ context }) => {
  const { page } = await enrolled(context, false)
  await run(page, 'M.provisionJoin()')
  expect((await run(page, 'M.joinQueuedClear()')).state).not.toBe('active')
  expect((await run(page, 'M.local()')).generation).toBeNull()
})
for (const mode of ['child', 'account', 'expiry', 'deadline']) test(`typed join suppresses committed effects after ${mode} during source lock release`, async ({ context }) => {
  const { page } = await enrolled(context, false)
  await run(page, 'M.provisionJoin()')
  expect(await run(page, `M.joinReleaseFault('${mode}')`)).toMatchObject({ state: 'pending', reason: 'stale' })
  expect((await run(page, 'M.local()')).generation).toBe('1')
  expect((await run(page, 'M.recoverJoin()')).value.outbox[0].destination.type).toBe('Introduction')
})
test('another tab clears a child during consent without publishing or saving late permission', async ({ context }) => {
  const { page } = await enrolled(context, false)
  await run(page, 'M.provisionJoin()'); await run(page, 'M.startWaitingJoin()')
  const other = await context.newPage(); await other.goto(origin)
  await run(other, 'M.clearJoinChild()')
  expect((await run(page, 'M.finishWaitingJoin()')).state).not.toBe('active')
  expect((await run(page, 'M.local()')).generation).toBeNull()
  expect((await run(page, 'M.joinPermissions()')).value.approved).toEqual([])
})
test('never-resolving typed join consent expires and a late approval saves no permission', async ({ context }) => {
  const { page } = await enrolled(context, false)
  await run(page, 'M.provisionJoin()')
  expect((await run(page, 'M.neverJoinConsent()')).state).not.toBe('active')
  expect((await run(page, 'M.local()')).generation).toBeNull()
  expect((await run(page, 'M.joinPermissions()')).value.approved).toEqual([])
})
test('typed join rejects a copied signature reply despite valid signature bytes', async ({ context }) => {
  const { page } = await enrolled(context, false)
  await run(page, 'M.provisionJoin()')
  expect(await run(page, 'M.forgedJoinSignature()')).toEqual({ state: 'refused', reason: 'unauthorised' })
  expect((await run(page, 'M.local()')).generation).toBeNull()
})
test('a repeated typed join operation cannot adopt a second pending session', async ({ context }) => {
  const { page } = await enrolled(context, false)
  await run(page, 'M.provisionJoin()')
  const first = await run(page, 'M.typedJoin()')
  expect(first.state).toBe('active')
  expect(await run(page, 'M.typedJoin()')).toEqual({ state: 'refused', reason: 'join-exists' })
  expect((await run(page, 'M.recoverJoin()')).value.session).toBe(first.value.session)
  expect((await run(page, 'M.discover()')).ids).toEqual([first.value.session])
})
for (const mode of ['cleanup', 'revision']) test(`typed join wipes unreleased effects when source ${mode} throws`, async ({ context }) => {
  const { page } = await enrolled(context, false)
  await run(page, 'M.provisionJoin()')
  expect(await run(page, `M.joinReleaseFault('${mode}')`)).toEqual({ error: `fixture source ${mode}`, wiped: true })
  expect((await run(page, 'M.local()')).generation).toBe('1')
  expect((await run(page, 'M.recoverJoin()')).value.outbox[0].destination.type).toBe('Introduction')
})
