import { test, expect, type BrowserContext } from '@playwright/test'
import { build } from 'esbuild'

const origin = 'https://browser-mls-grant-custody.kithmoot.test'
let bundle: string
test.beforeAll(async () => { bundle = (await build({ entryPoints: ['test/mls-grant-custody.browser-entry.ts'], bundle: true, write: false, format: 'iife', globalName: 'G', define: { 'import.meta.env.BASE_URL': '"/"' } })).outputFiles[0].text })
async function fixture(context: BrowserContext) {
  await context.route(origin + '/**', route => new URL(route.request().url()).pathname === '/fixture.js'
    ? route.fulfill({ contentType: 'text/javascript', body: bundle })
    : route.fulfill({ contentType: 'text/html', body: '<script src="/fixture.js"></script>' }))
  const page = await context.newPage(); await page.goto(origin)
  return page
}
test('empty grant custody gets an atomic non-extractable key and real version barrier', async ({ context }) => {
  const page = await fixture(context)
  expect(await page.evaluate('G.prepare()')).toEqual({ state: 'ready' })
  expect(await page.evaluate('G.inspect()')).toMatchObject({ database: 2, version: 2, extractable: false, value: { phase: 'ready', records: [] } })
  expect(await page.evaluate('G.all()')).toEqual([])
  expect(await page.evaluate('G.legacyOpen()')).toEqual({ accepted: false, name: 'VersionError' })
  await page.evaluate('G.put()')
  expect(await page.evaluate('G.all()')).toHaveLength(1)
})
for (const mode of ['key','record'] as const) test(`empty grant custody atomic ${mode} quota failure retains the original empty state`, async ({ context }) => {
  const page = await fixture(context)
  await page.evaluate(mode => (window as any).G.failNextWrite(mode), mode)
  expect(await page.evaluate('G.prepare()')).toEqual({ state: 'refused' })
  expect(await page.evaluate('G.inspect()')).toEqual({ database: 1, key: false, record: false })
  expect(await page.evaluate('G.prepare()')).toEqual({ state: 'ready' })
})
test('an idle cached legacy connection blocks the upgrade and an abandoned request cannot become ready', async ({ context }) => {
  const page = await fixture(context), records = await page.evaluate('G.seed()')
  expect(await page.evaluate('G.prepare()')).toEqual({ state: 'blocked' })
  expect(await page.evaluate('G.savedFence()')).toBe(2)
  expect(await page.evaluate('G.legacyPut()')).toEqual({ accepted: false })
  await page.evaluate('G.closeLegacy()')
  await expect.poll(async () => page.evaluate('G.inspect()')).toMatchObject({ value: { phase: 'fenced' } })
  await expect.poll(async () => page.evaluate('G.prepare()')).toEqual({ state: 'ready' })
  expect(await page.evaluate('G.all()')).toEqual(records)
  expect(await page.evaluate('G.legacyOpen()')).toEqual({ accepted: false, name: 'VersionError' })
})
test('a saved legacy key with no record is reused through migration', async ({ context }) => {
  const page = await fixture(context)
  await page.evaluate('G.emptyKey()'); await page.evaluate('G.closeLegacy()')
  expect(await page.evaluate('G.prepare()')).toEqual({ state: 'ready' })
  expect(await page.evaluate('G.inspect()')).toMatchObject({ database: 2, extractable: false, value: { records: [] } })
})
for (const mode of ['null','false','zero','empty','undefined'] as const) test(`present malformed ${mode} key custody is refused without replacement`, async ({ context }) => {
  const page = await fixture(context)
  await page.evaluate(mode => (window as any).G.malformedKey(mode), mode)
  const before = await page.evaluate('G.keySlot()')
  expect(before).toMatchObject({ database: 1, present: true, record: false })
  expect(await page.evaluate('G.prepare()')).toEqual({ state: 'refused' })
  await expect(page.evaluate('G.all()')).rejects.toThrow()
  await expect(page.evaluate('G.put()')).rejects.toThrow()
  expect(await page.evaluate('G.keySlot()')).toEqual(before)
})
test('a malformed key slot inserted after the custody read cannot be overwritten by the atomic fence write', async ({ context }) => {
  const page = await fixture(context)
  await page.evaluate('G.changeKeyBeforeFence()')
  expect(await page.evaluate('G.prepare()')).toEqual({ state: 'refused' })
  expect(await page.evaluate('G.keySlot()')).toEqual({ database: 1, present: true, value: null, record: false })
})
test('a blocked upgrade retains shared ownership until termination before another owner may retry', async ({ context }) => {
  const page = await fixture(context)
  await page.evaluate('G.seed()'); await page.evaluate('G.observeUpgrades()')
  expect(await page.evaluate('G.prepare()')).toEqual({ state: 'blocked' })
  await page.evaluate('void(window.second = G.secondPrepare())')
  await expect.poll(async () => (await page.evaluate('navigator.locks.query()') as any).pending
    .some((lock: any) => lock.name === 'kithmoot-vmls-grants-v1:migration-v2')).toBe(true)
  expect(await page.evaluate('G.upgrades()')).toBe(1)
  expect((await page.evaluate('navigator.locks.query()') as any).held
    .some((lock: any) => lock.name === 'kithmoot-vmls-grants-v1:migration-v2')).toBe(true)
  await page.evaluate('G.closeLegacy()')
  expect(await page.evaluate('window.second')).toEqual({ state: 'ready' })
  expect(await page.evaluate('G.upgrades()')).toBe(2)
  expect(await page.evaluate('G.inspect()')).toMatchObject({ database: 2, value: { phase: 'ready' } })
})
test('migration releases the store lock then drains a persisted legacy publisher through actual local settlement', async ({ context }) => {
  const page = await fixture(context), device = await page.evaluate('G.startWriter()')
  await expect.poll(async () => (await page.evaluate('G.progress()') as any).version).toBe(1)
  await page.evaluate('void(window.migration = G.prepare())')
  await expect.poll(async () => (await page.evaluate('G.progress()') as any).version).toBe(2)
  const progress = await page.evaluate('G.progress()') as any
  expect(progress.publications).toBe(0); expect(progress.cleanups).toBe(0)
  expect(progress.locks.pending.some((lock: any) => lock.name.endsWith('.' + device))).toBe(true)
  expect(progress.locks.held.some((lock: any) => lock.name === 'kithmoot-vmls-grants-v1')).toBe(false)
  expect(await page.evaluate('G.legacyPut(10)')).toEqual({ accepted: false })
  expect(await page.evaluate('G.freshLegacyWriter()')).toEqual({ accepted: false })
  expect(await page.evaluate('G.counters()')).toEqual({ publications: 0, cleanups: 0 })
  expect(await page.evaluate('G.finishWriter()')).toEqual({ saved: false })
  expect(await page.evaluate('window.migration')).toEqual({ state: 'blocked' })
  await page.evaluate('G.closeLegacy()')
  await expect.poll(async () => page.evaluate('G.prepare()')).toEqual({ state: 'ready' })
  expect(await page.evaluate('G.all()')).toMatchObject([{ device, state: 'installing' }])
  expect(await page.evaluate('G.counters()')).toEqual({ publications: 1, cleanups: 1 })
})
test('foreground invalidation leaves the durable fence without releasing a ready ledger', async ({ context }) => {
  const page = await fixture(context)
  await page.evaluate('G.startWriter()')
  await expect.poll(async () => (await page.evaluate('G.progress()') as any).version).toBe(1)
  await page.evaluate('void(window.migration = G.prepare())')
  await expect.poll(async () => (await page.evaluate('G.progress()') as any).version).toBe(2)
  await page.evaluate('G.stop()'); await page.evaluate('G.finishWriter()')
  expect(await page.evaluate('window.migration')).toEqual({ state: 'interrupted' })
  await page.evaluate('G.closeLegacy()')
  expect(await page.evaluate('G.inspect()')).toMatchObject({ database: 1, value: { phase: 'fenced' } })
  await page.evaluate('G.resume()')
  expect(await page.evaluate('G.prepare()')).toEqual({ state: 'ready' })
})
test('foreground abort during the ready transaction rolls it back to the exact durable fence', async ({ context }) => {
  const page = await fixture(context)
  await page.evaluate('G.stopOnReadyWrite()')
  expect(await page.evaluate('G.prepare()')).toEqual({ state: 'interrupted' })
  expect(await page.evaluate('G.inspect()')).toMatchObject({ database: 2, value: { phase: 'fenced', records: [] } })
  await expect(page.evaluate('G.all()')).rejects.toThrow('not ready')
  await page.evaluate('G.resume()')
  expect(await page.evaluate('G.prepare()')).toEqual({ state: 'ready' })
})
test('a maximum 2 MiB and 256-record legacy ledger migrates without losing signed custody', async ({ context }) => {
  const page = await fixture(context), expected = await page.evaluate('G.capacity()')
  expect(expected).toMatchObject({ count: 256, bytes: 2 * 1024 * 1024 })
  await page.evaluate('G.closeLegacy()')
  expect(await page.evaluate('G.prepare()')).toEqual({ state: 'ready' })
  expect(await page.evaluate('G.summary()')).toEqual(expected)
})
test('quota failure fencing a full ledger preserves its original ciphertext and key', async ({ context }) => {
  const page = await fixture(context)
  await page.evaluate('G.capacity()')
  const before = await page.evaluate('G.rawSummary()')
  await page.evaluate("G.failNextWrite('record')")
  expect(await page.evaluate('G.prepare()')).toEqual({ state: 'refused' })
  expect(await page.evaluate('G.rawSummary()')).toEqual(before)
})
for (const mode of ['missing-key','changed-key','legacy','missing-record'] as const) test(`ready custody refuses ${mode} evidence without reconstructing authority`, async ({ context }) => {
  const page = await fixture(context)
  await page.evaluate('G.seed()'); await page.evaluate('G.retainOriginal()'); await page.evaluate('G.closeLegacy()')
  expect(await page.evaluate('G.prepare()')).toEqual({ state: 'ready' })
  await page.evaluate(mode => (window as any).G.tamper(mode), mode)
  const before = await page.evaluate('G.rawSummary()')
  expect(await page.evaluate('G.prepare()')).toEqual({ state: 'refused' })
  await expect(page.evaluate('G.all()')).rejects.toThrow()
  await expect(page.evaluate('G.put()')).rejects.toThrow()
  expect(await page.evaluate('G.rawSummary()')).toEqual(before)
})
test('changed retained fence authority while draining cannot become ready', async ({ context }) => {
  const page = await fixture(context)
  await page.evaluate('G.startWriter()')
  await expect.poll(async () => (await page.evaluate('G.progress()') as any).version).toBe(1)
  await page.evaluate('void(window.migration = G.prepare())')
  await expect.poll(async () => (await page.evaluate('G.progress()') as any).version).toBe(2)
  await page.evaluate('G.changeFence()'); await page.evaluate('G.closeLegacy()'); await page.evaluate('G.finishWriter()')
  expect(await page.evaluate('window.migration')).toEqual({ state: 'refused' })
  expect(await page.evaluate('G.inspect()')).toMatchObject({ database: 2, value: { phase: 'fenced' } })
})
test('concurrent preparation owners serialize and preserve the original fence through upgrade', async ({ context }) => {
  const page = await fixture(context)
  await page.evaluate('G.startWriter()')
  await expect.poll(async () => (await page.evaluate('G.progress()') as any).version).toBe(1)
  await page.evaluate('void(window.first = G.prepare())')
  await expect.poll(async () => (await page.evaluate('G.progress()') as any).version).toBe(2)
  await page.evaluate('void(window.second = G.secondPrepare())')
  await expect.poll(async () => (await page.evaluate('G.progress()') as any).locks.pending.some((lock: any) => lock.name === 'kithmoot-vmls-grants-v1:migration-v2')).toBe(true)
  await page.evaluate('G.closeLegacy()'); await page.evaluate('G.finishWriter()')
  expect(await page.evaluate('window.first')).toEqual({ state: 'ready' })
  const before = await page.evaluate('G.rawSummary()')
  expect(await page.evaluate('window.second')).toEqual({ state: 'ready' })
  expect(await page.evaluate('G.rawSummary()')).toEqual(before)
  expect(await page.evaluate('G.counters()')).toEqual({ publications: 1, cleanups: 1 })
})
test('a replaced database version invalidates a cached ready connection without downgrading custody', async ({ context }) => {
  const page = await fixture(context)
  expect(await page.evaluate('G.prepare()')).toEqual({ state: 'ready' })
  const before = await page.evaluate('G.rawSummary()') as any
  await page.evaluate('G.advanceDatabaseSchema()')
  await expect(page.evaluate('G.all()')).rejects.toThrow()
  await expect(page.evaluate('G.put()')).rejects.toThrow()
  expect(await page.evaluate('G.prepare()')).toEqual({ state: 'refused' })
  expect(await page.evaluate('G.rawSummary()')).toEqual({ ...before, database: 3 })
})
