import { test, expect } from '@playwright/test'
import { createRoom, newDeviceContext, open, openCall } from './browser.js'

test('a viewer enlarges, pans and pops out a real received synthetic screen without stopping it', async ({ browser, baseURL }) => {
  const a = await newDeviceContext(browser, baseURL!), b = await newDeviceContext(browser, baseURL!)
  try {
    const presenter = await a.newPage(), viewer = await b.newPage()
    const link = await createRoom(presenter, baseURL!)
    await open(presenter, link, 'Ada'); await presenter.locator('#join').click(); await expect(presenter.locator('#roomArea')).toBeVisible()
    await open(viewer, link, 'Rowan'); await viewer.locator('#join').click(); await expect(viewer.locator('#roomArea')).toBeVisible()
    await openCall(presenter); await openCall(viewer)
    await presenter.locator('#toggleScreen').click()
    const expand = viewer.getByRole('button', { name: 'Expand screen share from Ada' })
    await expect(expand).toBeVisible({ timeout: 60000 }); await expand.click()
    const dialog = viewer.getByRole('dialog', { name: 'Screen-share viewer' })
    const video = dialog.locator('video')
    await expect.poll(() => video.evaluate((v: HTMLVideoElement) => v.videoWidth)).toBeGreaterThan(0)
    const previous = await video.evaluate((v: HTMLVideoElement) => v.currentTime)
    await expect.poll(() => video.evaluate((v: HTMLVideoElement) => v.currentTime)).toBeGreaterThan(previous)
    await dialog.getByRole('button', { name: 'Zoom in', exact: true }).click({ clickCount: 4 })
    const viewport = dialog.locator('.shareViewport')
    expect(Number(await viewport.getAttribute('data-zoom'))).toBeGreaterThan(2)
    const before = await video.getAttribute('style')
    const rect = (await viewport.boundingBox())!
    await viewer.mouse.move(rect.x + rect.width / 2, rect.y + rect.height / 2)
    await viewer.mouse.down(); await viewer.mouse.move(rect.x + rect.width / 2 + 90, rect.y + rect.height / 2 + 70, { steps: 5 }); await viewer.mouse.up()
    expect(await video.getAttribute('style')).not.toBe(before)
    await dialog.getByRole('button', { name: 'Fit to screen', exact: true }).click()
    await expect(viewport).toHaveAttribute('data-zoom', '1')
    await dialog.getByRole('button', { name: 'Fullscreen', exact: true }).click()
    await expect.poll(() => viewer.evaluate(() => Boolean(document.fullscreenElement))).toBe(true)
    await dialog.getByRole('button', { name: 'Exit fullscreen', exact: true }).click()
    const popupPromise = viewer.waitForEvent('popup')
    await dialog.getByRole('button', { name: 'Pop out', exact: true }).click()
    const popup = await popupPromise
    await expect.poll(() => popup.locator('video').evaluate((v: HTMLVideoElement) => v.videoWidth)).toBeGreaterThan(0)
    await popup.setViewportSize({ width: 700, height: 480 })
    expect(await popup.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await popup.getByRole('button', { name: 'Zoom in', exact: true }).click()
    await expect(popup.locator('.shareViewport')).toHaveAttribute('data-zoom', '1.25')
    await popup.close()
    await expect(presenter.locator('#toggleScreen')).toHaveAttribute('data-on', 'true')
    await expand.click()
    await expect.poll(() => video.evaluate((v: HTMLVideoElement) => v.videoWidth)).toBeGreaterThan(0)
    await presenter.locator('#toggleScreen').click()
    await expect(dialog).toContainText('Screen sharing has stopped or is reconnecting')
    expect(await video.evaluate((v: HTMLVideoElement) => v.srcObject)).toBe(null)
    await presenter.locator('#toggleScreen').click()
    await expect.poll(() => video.evaluate((v: HTMLVideoElement) => v.videoWidth)).toBeGreaterThan(0)
    await viewer.setViewportSize({ width: 320, height: 640 })
    expect(await viewer.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await viewer.screenshot({ path: '/tmp/kithmoot-share-viewer-320.png' })
    await dialog.getByRole('button', { name: 'Close screen-share viewer', exact: true }).click()
    await expect(presenter.locator('#toggleScreen')).toHaveAttribute('data-on', 'true')
    await viewer.evaluate(() => { window.open = () => null })
    await expand.click(); await dialog.getByRole('button', { name: 'Pop out', exact: true }).click()
    await expect(dialog).toContainText('The pop-out was blocked')
  } finally { await a.close(); await b.close() }
})
