// Moved to @forgesworn/fold-kit (see that package's EXTRACTION.md). Re-exported here,
// unchanged, so every existing import of `./epoch.js` keeps working.
export {
  EPOCH_ID_INFO,
  EPOCH_KEY_INFO,
  MAX_EPOCH,
  EPOCH_REQUEST_KEY_INFO,
  generateEpochSecret,
  deriveEpoch,
  encodeRekeyEvent,
  peekRekeyEvent,
  decodeRekeyEvent,
  deriveEpochRequestKey,
  epochRequestAdmission,
  encodeEpochRequest,
  decodeEpochRequest,
  encodeEpochGrant,
  decodeEpochGrant,
  hostRoomEpoch,
  EpochRefusedError,
  requestRoomEpoch,
  canonicalAdmins,
  CHANNEL_NAME,
  RESERVED_CHANNELS,
  canonicalChannels,
  signChannels,
  verifyChannels,
  signAdmins,
  verifyAdmins,
  EPOCH_LABELS,
} from '@forgesworn/fold-kit'
export type {
  RoomEpoch,
  EpochKeys,
  EncodeRekeyOptions,
  RekeyNotice,
  PeekRekeyOptions,
  DecodeRekeyOptions,
  EpochRequestAdmissionOptions,
  EncodeEpochRequestOptions,
  DecodeEpochRequestOptions,
  EpochRequest,
  EpochRefusal,
  EncodeEpochGrantOptions,
  DecodeEpochGrantOptions,
  EpochGrant,
  HostRoomEpochOptions,
  RequestRoomEpochOptions,
  SignAdminsOptions,
  VerifyAdminsOptions,
  SignChannelsOptions,
  VerifyChannelsOptions,
} from '@forgesworn/fold-kit'
