// Moved to @forgesworn/fold-kit (see that package's EXTRACTION.md). Re-exported here,
// unchanged, so every existing import of `./invitation.js` keeps working.
export {
  INVITATION_DELEGATION_TTL_SECONDS,
  MAX_INVITATION_DELEGATION_DEPTH,
  createRoomInvitation,
  roomInvitation,
  deriveInvitationId,
  encodeInvitationRequest,
  decodeInvitationRequest,
  verifyInvitationDelegation,
  encodeInvitationGrant,
  decodeRoomAdmissionGrant,
  decodeInvitationGrant,
  ROOM_ENDED_MESSAGE,
  encodeInvitationRetirement,
  decodeInvitationRetirement,
  decodeInvitationRetirementNotice,
  retirementError,
  hostRoomInvitation,
  requestRoomAdmissionCapability,
  requestRoomAdmission,
  INVITATION_LABELS,
} from '@forgesworn/fold-kit'
export type {
  RoomInvitation,
  RoomInvitationHost,
  InvitationDelegation,
  RoomInvitationDelegate,
  RoomAdmission,
  EncodeInvitationRequestOptions,
  InvitationRequest,
  DecodeInvitationRequestOptions,
  EncodeInvitationGrantOptions,
  DecodeInvitationGrantOptions,
  HostRoomInvitationOptions,
  EncodeInvitationRetirementOptions,
  RequestRoomAdmissionOptions,
} from '@forgesworn/fold-kit'
