// Freezes every `kithmoot/` string in `src/` - HKDF info strings, message
// domain prefixes and content-version markers - so an accidental rename
// during the circle-kit extraction (see
// docs/plans/2026-09-28-circle-kit-extraction.md §3.2 in the girnel
// repository) shows up here rather than as a silent wire-format change.
// These are protocol names now, not branding: the plan's §1.4 "app-specific
// tangles" table keeps every one of them byte-identical when the code that
// uses them moves to the shared kit.
//
// This test does not care which module a label lives in, only that the
// full set found by scanning `src/*.ts` (excluding `.test.ts` files and
// this file) exactly matches the frozen list below. Adding, removing or
// editing a label anywhere in `src/` fails this test until the list is
// updated deliberately.
import { describe, expect, it } from 'vitest'
import { readFileSync, readdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))

/** Matches a `kithmoot/...` literal up to (but not including) the next
 *  character outside its alphabet - so a template literal's `${...}`
 *  interpolation is captured only up to its own fixed prefix, e.g.
 *  `` `kithmoot/v1/admins:${roomId}` `` yields `kithmoot/v1/admins:`. */
const LABEL_PATTERN = /kithmoot\/[A-Za-z0-9/_.:-]*/g

function findLabels(): Set<string> {
  const found = new Set<string>()
  for (const entry of readdirSync(here)) {
    if (!entry.endsWith('.ts') || entry.endsWith('.test.ts')) continue
    const text = readFileSync(join(here, entry), 'utf8')
    for (const match of text.matchAll(LABEL_PATTERN)) found.add(match[0])
  }
  return found
}

/**
 * The full, frozen set of `kithmoot/` wire-format strings across `src/`, as
 * of the circle-kit extraction plan. Generated by scanning every non-test
 * file in `src/` for `kithmoot/[A-Za-z0-9/_.:-]*` and sorting the result -
 * see `findLabels` above, which this test re-derives independently on every
 * run.
 */
const FROZEN_LABELS: readonly string[] = [
  'kithmoot/assignment/v1',
  // The bare namespace prefix: used on its own inside `den-client.ts`'s
  // `den/kithmoot/v1/${purpose}` HKDF info string (the den's own root,
  // salted by "den/" ahead of it), and referred to in prose elsewhere as
  // "every other `kithmoot/v1/*` label".
  'kithmoot/v1/',
  'kithmoot/v1/admins:',
  'kithmoot/v1/agent-owner:',
  'kithmoot/v1/assist',
  'kithmoot/v1/call-bell',
  'kithmoot/v1/call-bell-key',
  'kithmoot/v1/call-bell-tag',
  'kithmoot/v1/call-bell:',
  'kithmoot/v1/channel-id/',
  'kithmoot/v1/channel-key/',
  'kithmoot/v1/channels:',
  'kithmoot/v1/epoch-id',
  'kithmoot/v1/epoch-key',
  'kithmoot/v1/epoch-request-key',
  'kithmoot/v1/epoch-request:',
  'kithmoot/v1/forwarder-key',
  'kithmoot/v1/kindred:',
  'kithmoot/v1/media-key',
  'kithmoot/v1/pairing',
  'kithmoot/v1/read-position-id',
  'kithmoot/v1/room-id',
  'kithmoot/v1/room-key',
  'kithmoot/v1/verify',
  'kithmoot/v2/invitation-delegation:',
  'kithmoot/v2/invitation-id',
  'kithmoot/v2/invitation-request-key',
  'kithmoot/v3/group-invitation-key',
]

describe('kithmoot/ wire-format labels', () => {
  it('src/ carries exactly the frozen set of labels, no more and no fewer', () => {
    const found = [...findLabels()].sort()
    expect(found).toEqual([...FROZEN_LABELS].sort())
  })

  it('every label starts with a version segment, so a future unversioned string cannot slip in unnoticed', () => {
    for (const label of FROZEN_LABELS) {
      expect(label).toMatch(/^kithmoot\/(v[0-9]+\/|assignment\/v[0-9]+$)/)
    }
  })

  it('the frozen list itself has no duplicates', () => {
    expect(new Set(FROZEN_LABELS).size).toBe(FROZEN_LABELS.length)
  })
})
