// Freezes every `kithmoot/` string in `src/` - HKDF info strings, message
// domain prefixes and content-version markers - so an accidental rename
// during the circle-kit extraction (see
// @forgesworn/fold-kit's EXTRACTION.md) shows up here rather than as a silent wire-format change.
// These are protocol names now, not branding: the plan's §1.4 "app-specific
// tangles" table keeps every one of them byte-identical when the code that
// uses them moves to the shared kit.
//
// Since the T2.1 codec cutover, some of these labels no longer have their
// literal text anywhere in this repository: the modules that owned them
// (`access.ts`, `epoch.ts`, `invitation.ts`, `persistent-invitation.ts`,
// `room.ts`, and `chat.ts`'s `CHANNEL_ID_INFO`/`CHANNEL_KEY_INFO`) became
// re-export shims onto @forgesworn/fold-kit, and the literal strings live in
// that package's own source instead. This test therefore checks two
// disjoint sets: `FROZEN_LOCAL_LABELS`, still found by scanning `src/*.ts`
// here, and `FROZEN_KIT_LABELS`, checked by asserting the re-exported
// constants equal their pinned values (the kit's own `src/labels.test.ts`
// is what scans ITS text for those). Together they are exactly the wire
// format's full, frozen label set - nothing was renamed, only relocated.
import { describe, expect, it } from 'vitest'
import { readFileSync, readdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

import { ACCESS_LABELS } from './access.js'
import { ASSIGNMENT_LABELS } from './assignments.js'
import { CALL_BELL_LABELS } from './call-bell.js'
import { CHAT_LABELS, CHANNEL_ID_INFO, CHANNEL_KEY_INFO } from './chat.js'
import { DEN_CLIENT_LABELS } from './den-client.js'
import { EPOCH_LABELS, EPOCH_ID_INFO, EPOCH_KEY_INFO } from './epoch.js'
import { EPOCH_COMMIT_LABELS } from './epoch-commit.js'
import { FORWARDER_LABELS } from './forwarder.js'
import { INVITATION_LABELS } from './invitation.js'
import { MEDIA_CRYPTO_LABELS } from './media-crypto.js'
import { MEETING_LABELS } from './meeting.js'
import { MEMBER_EPOCH_LABELS } from './member-epoch.js'
import { OWNERSHIP_LABELS } from './ownership.js'
import { PEER_ASSIST_LABELS } from './peer-assist.js'
import { PAIRING_LABELS } from './pairing.js'
import { PERSISTENT_INVITATION_LABELS } from './persistent-invitation.js'
import { READ_POSITION_LABELS } from './read-position.js'
import { ROOM_LABELS } from './room.js'
import { ROOM_RELAYS_LABELS } from './room-relays.js'
import { VERIFICATION_LABELS } from './verification.js'
import { VMLS_REVOCATION_LABELS } from './vmls-revocation-request.js'

const here = dirname(fileURLToPath(import.meta.url))

/** Matches a `kithmoot/...` literal up to (but not including) the next
 *  character outside its alphabet - so a template literal's `${...}`
 *  interpolation is captured only up to its own fixed prefix, e.g.
 *  `` `kithmoot/v1/admins:${roomId}` `` yields `kithmoot/v1/admins:`. */
const LABEL_PATTERN = /kithmoot\/[A-Za-z0-9/_.:-]*/g

function findLabels(): Set<string> {
  const found = new Set<string>()
  for (const entry of readdirSync(here)) {
    if (!entry.endsWith('.ts') || entry.endsWith('.test.ts')) continue
    const text = readFileSync(join(here, entry), 'utf8')
    for (const match of text.matchAll(LABEL_PATTERN)) found.add(match[0])
  }
  return found
}

/**
 * The wire-format strings whose literal text still lives somewhere in this
 * repository's `src/`, owned by a module that stayed. Generated by scanning
 * every non-test file in `src/` for `kithmoot/[A-Za-z0-9/_.:-]*` and sorting
 * the result - see `findLabels` above, which this test re-derives
 * independently on every run. `kithmoot/v1/room-id` and
 * `kithmoot/v1/room-key` are still found here even though `room.ts` itself
 * moved: `media-crypto.ts` (which stayed) derives its media key from the
 * same two literal HKDF info strings, by design (see its own header
 * comment), so they remain physically present in this directory.
 */
const FROZEN_LOCAL_LABELS: readonly string[] = [
  'kithmoot/assignment/v1',
  // The bare namespace prefix: used on its own inside `den-client.ts`'s
  // `den/kithmoot/v1/${purpose}` HKDF info string (the den's own root,
  // salted by "den/" ahead of it), and referred to in prose elsewhere as
  // "every other `kithmoot/v1/*` label".
  'kithmoot/v1/',
  'kithmoot/v1/agent-owner:',
  'kithmoot/v1/assist',
  'kithmoot/v1/call-bell',
  'kithmoot/v1/call-bell-key',
  'kithmoot/v1/call-bell-tag',
  'kithmoot/v1/call-bell:',
  'kithmoot/v1/forwarder-key',
  'kithmoot/v1/media-key',
  'kithmoot/v1/meeting:',
  'kithmoot/v1/pairing',
  'kithmoot/v1/read-position-id',
  'kithmoot/v1/recording:',
  'kithmoot/v1/recording-capture:',
  'kithmoot/v1/relays:',
  'kithmoot/v1/room-id',
  'kithmoot/v1/room-key',
  'kithmoot/v1/verify',
  'kithmoot/vmls-member-grant/v1',
]

/**
 * The wire-format strings owned exclusively by @forgesworn/fold-kit since
 * T2.1: `access.ts`, `epoch.ts`, `invitation.ts` and
 * `persistent-invitation.ts` re-export these constants unchanged, so each is
 * checked below by asserting the imported constant still equals this pinned
 * value, module by module, rather than by scanning this repository's text.
 * `room.ts`'s two labels (`kithmoot/v1/room-id`, `kithmoot/v1/room-key`) are
 * NOT listed here even though `room.ts` also moved: they stay physically
 * present in `src/` via `media-crypto.ts` (see `FROZEN_LOCAL_LABELS`), so
 * `ROOM_LABELS` is checked against that shared value directly instead.
 */
const FROZEN_KIT_ONLY_LABELS: readonly string[] = [
  'kithmoot/v1/admins:',
  'kithmoot/v1/channels:',
  'kithmoot/v1/epoch-commit:',
  'kithmoot/v1/epoch-id',
  'kithmoot/v1/epoch-key',
  'kithmoot/v1/epoch-request-key',
  'kithmoot/v1/epoch-request:',
  'kithmoot/v1/kindred:',
  'kithmoot/v1/member-epoch-request-key',
  'kithmoot/v2/invitation-delegation:',
  'kithmoot/v2/invitation-id',
  'kithmoot/v2/invitation-request-key',
  'kithmoot/v3/group-invitation-key',
]

/**
 * `CHANNEL_ID_INFO`/`CHANNEL_KEY_INFO` moved into @forgesworn/fold-kit's
 * `channel.ts` as part of `CHANNEL_LABELS`, which `chat.ts`'s shim
 * deliberately does NOT re-export (see EXTRACTION.md's "For KithMoot's
 * cutover" notes: `CHANNEL_LABELS` would collide with this file's own,
 * unrelated `CHAT_LABELS`). So neither constant is checked here by name;
 * their exact values are pinned instead by the "composed labels" block
 * below, via `CHANNEL_ID_INFO`/`CHANNEL_KEY_INFO`, which `chat.ts` does
 * re-export.
 */
const FROZEN_KIT_CHANNEL_LABELS: readonly string[] = ['kithmoot/v1/channel-id/', 'kithmoot/v1/channel-key/']

/** The full, frozen wire-format label set: local and kit-owned together. */
const FROZEN_LABELS: readonly string[] = [
  ...FROZEN_LOCAL_LABELS,
  ...FROZEN_KIT_ONLY_LABELS,
  ...FROZEN_KIT_CHANNEL_LABELS,
]

describe('kithmoot/ wire-format labels', () => {
  it('src/ carries exactly the frozen set of LOCAL labels, no more and no fewer', () => {
    const found = [...findLabels()].sort()
    expect(found).toEqual([...FROZEN_LOCAL_LABELS].sort())
  })

  it('every label starts with a version segment, so a future unversioned string cannot slip in unnoticed', () => {
    for (const label of FROZEN_LABELS) {
      // The Vennel section 7.1 member-grant reference and the assignment
      // protocol predate this repository's prefix-version convention; both
      // carry their frozen version at the end instead.
      expect(label).toMatch(/^kithmoot\/(v[0-9]+\/|assignment\/v[0-9]+$|vmls-member-grant\/v[0-9]+$)/)
    }
  })

  it('the frozen list itself has no duplicates', () => {
    expect(new Set(FROZEN_LABELS).size).toBe(FROZEN_LABELS.length)
  })
})

// ===========================================================================
// Per-module: each locally-owned label-bearing module exports its own
// frozen list (`CALL_BELL_LABELS`, `FORWARDER_LABELS`, ...), and this checks
// each one against a scan of THAT module's own file, rather than scanning
// `src/*.ts` as a whole (which the tests above do, and which is blind to
// comments: a label renamed in code but left quoted in a stale comment
// still passes there). A label moved out of a file has to be removed from
// that file's own exported list at the same time, or this fails - unlike a
// whole-directory scan, which cannot tell "moved to another file in src/"
// from "renamed everywhere it is quoted".
//
// `access.ts`, `epoch.ts`, `invitation.ts`, `persistent-invitation.ts` and
// `room.ts` are NOT in this list: since T2.1 they are pure re-export shims
// onto @forgesworn/fold-kit and own no label text of their own any more -
// see the "labels moved to @forgesworn/fold-kit" block below instead.
// `chat.ts` stays in this list with an empty `CHAT_LABELS`: its own two
// labels (`CHANNEL_ID_INFO`, `CHANNEL_KEY_INFO`) moved with `deriveChannel`,
// and nothing replaced them.
// ===========================================================================

const MODULE_LABEL_LISTS: ReadonlyArray<readonly [string, readonly string[]]> = [
  ['assignments.ts', ASSIGNMENT_LABELS],
  ['call-bell.ts', CALL_BELL_LABELS],
  ['chat.ts', CHAT_LABELS],
  ['den-client.ts', DEN_CLIENT_LABELS],
  ['forwarder.ts', FORWARDER_LABELS],
  ['media-crypto.ts', MEDIA_CRYPTO_LABELS],
  ['meeting.ts', MEETING_LABELS],
  ['ownership.ts', OWNERSHIP_LABELS],
  ['peer-assist.ts', PEER_ASSIST_LABELS],
  ['pairing.ts', PAIRING_LABELS],
  ['read-position.ts', READ_POSITION_LABELS],
  ['room-relays.ts', ROOM_RELAYS_LABELS],
  ['verification.ts', VERIFICATION_LABELS],
  ['vmls-revocation-request.ts', VMLS_REVOCATION_LABELS],
]

function findLabelsInFile(file: string): string[] {
  const text = readFileSync(join(here, file), 'utf8')
  const found = new Set<string>()
  for (const match of text.matchAll(LABEL_PATTERN)) found.add(match[0])
  return [...found].sort()
}

describe('per-module label exports (checked against exported constants, not comment text)', () => {
  for (const [file, exported] of MODULE_LABEL_LISTS) {
    it(`${file}'s exported label list matches a fresh scan of ${file} alone`, () => {
      expect([...exported].sort()).toEqual(findLabelsInFile(file))
    })
  }

  it('the union of every LOCAL module\'s own exported list is exactly the local frozen set above', () => {
    const union = new Set<string>()
    for (const [, exported] of MODULE_LABEL_LISTS) for (const label of exported) union.add(label)
    expect([...union].sort()).toEqual([...FROZEN_LOCAL_LABELS].sort())
  })

  it('no local label is claimed by more than one module\'s exported list, except the bare namespace prefix', () => {
    // 'kithmoot/v1/' is the one deliberate exception: den-client.ts uses it
    // on its own inside `den/kithmoot/v1/${purpose}`, and it is also the
    // literal prefix of every OTHER `kithmoot/v1/*` label - see the comment
    // on FROZEN_LOCAL_LABELS above. Every module using it as a genuine
    // standalone literal (rather than as a substring of a longer, versioned
    // label) legitimately owns it.
    // 'kithmoot/v1/room-id' and 'kithmoot/v1/room-key' are claimed only by
    // media-crypto.ts now (room.ts moved to the kit), so no exception is
    // needed for them any more; kept here in case a future module needs one.
    const SHARED_EXCEPTIONS = new Set(['kithmoot/v1/'])
    const owners = new Map<string, string[]>()
    for (const [file, exported] of MODULE_LABEL_LISTS) {
      for (const label of exported) {
        const existing = owners.get(label) ?? []
        if (existing.length > 0 && !SHARED_EXCEPTIONS.has(label)) {
          expect.fail(`"${label}" is claimed by both ${existing.join(', ')} and ${file}`)
        }
        owners.set(label, [...existing, file])
      }
    }
  })
})

// ===========================================================================
// Labels moved to @forgesworn/fold-kit (T2.1): the constants below are
// re-exported unchanged from KithMoot's shim files, which own no label text
// of their own any more - so these are checked by value, against the kit's
// pinned frozen list, rather than by scanning this repository's text.
// ===========================================================================

describe('labels moved to @forgesworn/fold-kit (re-exported unchanged, no longer local text)', () => {
  it('ACCESS_LABELS (access.ts)', () => {
    expect([...ACCESS_LABELS].sort()).toEqual(['kithmoot/v1/kindred:'])
  })

  it('ROOM_LABELS (room.ts)', () => {
    expect([...ROOM_LABELS].sort()).toEqual(['kithmoot/v1/room-id', 'kithmoot/v1/room-key'])
  })

  it('EPOCH_LABELS (epoch.ts)', () => {
    expect([...EPOCH_LABELS].sort()).toEqual([
      'kithmoot/v1/admins:',
      'kithmoot/v1/channels:',
      'kithmoot/v1/epoch-id',
      'kithmoot/v1/epoch-key',
      'kithmoot/v1/epoch-request-key',
      'kithmoot/v1/epoch-request:',
    ])
  })

  it('EPOCH_COMMIT_LABELS (epoch-commit.ts)', () => {
    expect([...EPOCH_COMMIT_LABELS].sort()).toEqual(['kithmoot/v1/epoch-commit:'])
  })

  it('MEMBER_EPOCH_LABELS (member-epoch.ts)', () => {
    expect([...MEMBER_EPOCH_LABELS].sort()).toEqual(['kithmoot/v1/member-epoch-request-key'])
  })

  it('INVITATION_LABELS (invitation.ts)', () => {
    expect([...INVITATION_LABELS].sort()).toEqual([
      'kithmoot/v2/invitation-delegation:',
      'kithmoot/v2/invitation-id',
      'kithmoot/v2/invitation-request-key',
    ])
  })

  it('PERSISTENT_INVITATION_LABELS (persistent-invitation.ts)', () => {
    expect([...PERSISTENT_INVITATION_LABELS].sort()).toEqual(['kithmoot/v3/group-invitation-key'])
  })

  it('the union of the kit-exclusive lists is exactly FROZEN_KIT_ONLY_LABELS (ROOM_LABELS excluded: its two labels are already counted in FROZEN_LOCAL_LABELS, checked above)', () => {
    const union = new Set<string>([
      ...ACCESS_LABELS,
      ...EPOCH_LABELS,
      ...EPOCH_COMMIT_LABELS,
      ...MEMBER_EPOCH_LABELS,
      ...INVITATION_LABELS,
      ...PERSISTENT_INVITATION_LABELS,
    ])
    expect([...union].sort()).toEqual([...FROZEN_KIT_ONLY_LABELS].sort())
  })
})

// ===========================================================================
// Composed labels: `deriveEpoch`'s per-epoch info strings and
// `deriveChannel`'s per-channel info strings are built by string
// concatenation at their call site (`` `${EPOCH_ID_INFO}/${n}` ``,
// `CHANNEL_ID_INFO + channel`), so neither the whole-file scan above nor a
// module's own frozen list (which records only the fixed PREFIX) pins the
// exact bytes a real epoch or channel derivation signs/encrypts under. These
// check the real exported constants - re-exported unchanged from
// @forgesworn/fold-kit since T2.1 - compose to exactly what
// `vectors/kithmoot-vectors.json` and `vectors/circle-vectors.json` already
// exercise, independent of any vector file.
// ===========================================================================

describe('composed labels (info strings built by concatenation, not a fixed literal)', () => {
  it('deriveEpoch composes EPOCH_ID_INFO/EPOCH_KEY_INFO with "/" + the epoch number', () => {
    expect(`${EPOCH_ID_INFO}/1`).toBe('kithmoot/v1/epoch-id/1')
    expect(`${EPOCH_KEY_INFO}/1`).toBe('kithmoot/v1/epoch-key/1')
    expect(`${EPOCH_ID_INFO}/2`).toBe('kithmoot/v1/epoch-id/2')
    expect(`${EPOCH_ID_INFO}/1`).not.toBe(`${EPOCH_ID_INFO}/2`)
  })

  it('deriveChannel composes CHANNEL_ID_INFO/CHANNEL_KEY_INFO directly with the channel name (no separator)', () => {
    expect(CHANNEL_ID_INFO + 'planning').toBe('kithmoot/v1/channel-id/planning')
    expect(CHANNEL_KEY_INFO + 'planning').toBe('kithmoot/v1/channel-key/planning')
    expect(CHANNEL_ID_INFO + 'planning').not.toBe(CHANNEL_ID_INFO + 'social')
  })
})
